__version__ = "0.2.5"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.2.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '6bd835605bcf504c5c50f1c120df1af371d75559'
__git_head_subject__ = 'Finished release v0.2.5.'
__git_head_message__ = ''
__git_dirty_diff__ = ''