# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='services/another_service.proto',
  package='',
  serialized_pb='\n\x1eservices/another_service.proto\"\'\n\x10PBAnotherRequest\x12\x13\n\x0brequest_str\x18\x01 \x02(\t\")\n\x11PBAnotherResponse\x12\x14\n\x0cresponse_str\x18\x01 \x02(\t')




_PBANOTHERREQUEST = descriptor.Descriptor(
  name='PBAnotherRequest',
  full_name='PBAnotherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request_str', full_name='PBAnotherRequest.request_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=73,
)


_PBANOTHERRESPONSE = descriptor.Descriptor(
  name='PBAnotherResponse',
  full_name='PBAnotherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='response_str', full_name='PBAnotherResponse.response_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['PBAnotherRequest'] = _PBANOTHERREQUEST
DESCRIPTOR.message_types_by_name['PBAnotherResponse'] = _PBANOTHERRESPONSE

class PBAnotherRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBANOTHERREQUEST
  
  # @@protoc_insertion_point(class_scope:PBAnotherRequest)

class PBAnotherResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBANOTHERRESPONSE
  
  # @@protoc_insertion_point(class_scope:PBAnotherResponse)

# @@protoc_insertion_point(module_scope)
