__version__ = "0.6.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.6.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '03d9b338589010ca9132dd9cb7ee6e465d707c45'
__git_head_subject__ = 'TRIVIAL fixing previous commit'
__git_head_message__ = ''
__git_dirty_diff__ = ''