
# parsetabs/regex_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'sFW\xd1\xa2\x17z\xa0:\x026\x1d\x12\xfa\\\x0b'
    
_lr_action_items = {'REGEX':([0,],[1,]),'BIN':([1,],[15,]),'HOSTNAME':([1,],[22,]),'WORD':([1,],[12,]),'NEQ':([4,5,6,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,],[-22,-2,-20,-12,-23,-16,26,-1,-9,28,-15,-19,-4,-24,-3,-21,-6,-11,-25,]),'REGULAR_EXPRESSION':([1,25,26,27,28,],[5,5,5,5,5,]),'NBSTR':([1,],[13,]),'FLOAT':([1,],[4,]),'HEX':([1,],[17,]),'ID':([1,],[20,]),'INT':([1,],[21,]),'LITERAL':([1,],[18,]),'INTERNAL_FIELD':([1,],[19,]),'WILDCARD':([1,],[23,]),'DEFAULT_FIELD':([1,],[9,]),'EQ':([4,5,6,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,],[-22,-2,-20,-12,-23,-16,25,-1,-9,27,-15,-19,-4,-24,-3,-21,-6,-11,-25,]),'OCT':([1,],[10,]),'DEFAULT_DATETIME_FIELD':([1,],[24,]),'$end':([2,3,5,7,11,16,29,30,31,32,],[0,-5,-2,-7,-10,-8,-14,-18,-13,-17,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'regex':([1,25,26,27,28,],[11,29,30,31,32,]),'cmdexpr':([0,],[2,]),'regex_nofield':([1,],[16,]),'int':([1,],[6,]),'regex_field':([1,],[7,]),'field':([1,],[14,]),'num':([1,],[8,]),'regexcmd':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('field -> WORD','field',1,'p_field_word','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',5),
  ('regex -> REGULAR_EXPRESSION','regex',1,'p_regex_regular_expression','/Users/salspaugh/splparser/splparser/rules/common/regexrules.py',5),
  ('field -> ID','field',1,'p_field_id','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',9),
  ('field -> LITERAL','field',1,'p_field_literal','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',13),
  ('cmdexpr -> regexcmd','cmdexpr',1,'p_cmdexpr_regex','/Users/salspaugh/splparser/splparser/rules/regexrules.py',14),
  ('field -> HOSTNAME','field',1,'p_field_hostname','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',17),
  ('regexcmd -> REGEX regex_field','regexcmd',2,'p_regexcmd_regex','/Users/salspaugh/splparser/splparser/rules/regexrules.py',18),
  ('regexcmd -> REGEX regex_nofield','regexcmd',2,'p_regexcmd_regex','/Users/salspaugh/splparser/splparser/rules/regexrules.py',19),
  ('field -> NBSTR','field',1,'p_field_nbstr','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',21),
  ('regex_nofield -> regex','regex_nofield',1,'p_regex','/Users/salspaugh/splparser/splparser/rules/regexrules.py',24),
  ('field -> WILDCARD','field',1,'p_field_wildcard','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',25),
  ('field -> num','field',1,'p_field_num','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',29),
  ('regex_field -> field EQ regex','regex_field',3,'p_regex_eq','/Users/salspaugh/splparser/splparser/rules/regexrules.py',31),
  ('regex_field -> regex EQ regex','regex_field',3,'p_regex_eq','/Users/salspaugh/splparser/splparser/rules/regexrules.py',32),
  ('num -> BIN','num',1,'p_num_bin','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',33),
  ('num -> OCT','num',1,'p_num_oct','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',37),
  ('regex_field -> field NEQ regex','regex_field',3,'p_regex_neq','/Users/salspaugh/splparser/splparser/rules/regexrules.py',40),
  ('regex_field -> regex NEQ regex','regex_field',3,'p_regex_neq','/Users/salspaugh/splparser/splparser/rules/regexrules.py',41),
  ('num -> HEX','num',1,'p_num_hex','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',41),
  ('num -> int','num',1,'p_num_int','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',45),
  ('int -> INT','int',1,'p_posint','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',49),
  ('num -> FLOAT','num',1,'p_num_float','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',53),
  ('field -> DEFAULT_FIELD','field',1,'p_field_default_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',57),
  ('field -> INTERNAL_FIELD','field',1,'p_field_internal_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',61),
  ('field -> DEFAULT_DATETIME_FIELD','field',1,'p_field_default_datetime_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',65),
]
