
# parsetabs/transpose_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xac\xfbF%\xff~\x8b8\xf5\xed\x9a?\xcf|CR'
    
_lr_action_items = {'INT':([3,],[4,]),'TRANSPOSE':([0,],[3,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[1,]),'transposecmd':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('cmdexpr -> transposecmd','cmdexpr',1,'p_cmdexpr_transpose','/Users/salspaugh/splparser/splparser/rules/transposerules.py',14),
  ('transposecmd -> TRANSPOSE','transposecmd',1,'p_cmdexpr_transpose_debug','/Users/salspaugh/splparser/splparser/rules/transposerules.py',18),
  ('transposecmd -> TRANSPOSE INT','transposecmd',2,'p_transpose_int','/Users/salspaugh/splparser/splparser/rules/transposerules.py',22),
]
