
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.3'
version_full = '6acf3d85db9f7fe439087c6cfb08adacae9d4d98'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

