#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `project_issue_sheet` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-project-issue-sheet",
    version = "7.0.355",
    description = "Timesheet on Issues",
    long_description = 
"""

This module adds the Timesheet support for the Issues/Bugs Management in Project.
=================================================================================

Worklogs can be maintained to signify number of hours spent by users to handle an issue.
                
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.project_issue_sheet': ".",
    },
    packages = ["openerp.addons.project_issue_sheet"],
    package_data = {
        'openerp.addons.project_issue_sheet': ["i18n/*.po*","project_issue_sheet_view.xml","images/project_issue_sheet_worklog.jpeg","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/es_VE.po","i18n/ja.po","i18n/ro.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/tr.po","i18n/de.po","i18n/hu.po","i18n/gl.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","security/ir.model.access.csv","project_issue_sheet_view.xml","security/ir.model.access.csv"],
    },
    install_requires = ["openerp-project-issue","openerp-hr-timesheet-sheet"],
    tests_require = ["unittest2"],
)
