# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/import.ui'
#
# Created: Wed Dec 18 15:05:16 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Import(object):
    def setupUi(self, Import):
        Import.setObjectName("Import")
        Import.resize(672, 504)
        self.gridLayout = QtGui.QGridLayout(Import)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(Import)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.accountTypeComboBox = QtGui.QComboBox(Import)
        self.accountTypeComboBox.setObjectName("accountTypeComboBox")
        self.gridLayout.addWidget(self.accountTypeComboBox, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(469, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.view = QtGui.QTreeView(Import)
        self.view.setObjectName("view")
        self.gridLayout.addWidget(self.view, 1, 0, 1, 3)
        self.frame = QtGui.QFrame(Import)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.selectedCounter = QtGui.QLabel(self.frame)
        self.selectedCounter.setObjectName("selectedCounter")
        self.horizontalLayout.addWidget(self.selectedCounter)
        spacerItem1 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.toImportCounter = QtGui.QLabel(self.frame)
        self.toImportCounter.setObjectName("toImportCounter")
        self.horizontalLayout.addWidget(self.toImportCounter)
        spacerItem2 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.importedCounter = QtGui.QLabel(self.frame)
        self.importedCounter.setObjectName("importedCounter")
        self.horizontalLayout.addWidget(self.importedCounter)
        spacerItem3 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.errorsCounter = QtGui.QLabel(self.frame)
        self.errorsCounter.setObjectName("errorsCounter")
        self.horizontalLayout.addWidget(self.errorsCounter)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 3)
        self.CsvImport = QtGui.QWidget(Import)
        self.CsvImport.setObjectName("CsvImport")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.CsvImport)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtGui.QProgressBar(self.CsvImport)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.selectAllButton = QtGui.QPushButton(self.CsvImport)
        self.selectAllButton.setObjectName("selectAllButton")
        self.horizontalLayout_2.addWidget(self.selectAllButton)
        self.importCancelButton = QtGui.QPushButton(self.CsvImport)
        self.importCancelButton.setObjectName("importCancelButton")
        self.horizontalLayout_2.addWidget(self.importCancelButton)
        self.closeButton = QtGui.QPushButton(self.CsvImport)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.gridLayout.addWidget(self.CsvImport, 3, 0, 1, 3)

        self.retranslateUi(Import)
        QtCore.QMetaObject.connectSlotsByName(Import)

    def retranslateUi(self, Import):
        Import.setWindowTitle(QtGui.QApplication.translate("Import", "Import CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Import", "Select account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Import", "selected:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedCounter.setText(QtGui.QApplication.translate("Import", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Import", "available:", None, QtGui.QApplication.UnicodeUTF8))
        self.toImportCounter.setText(QtGui.QApplication.translate("Import", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Import", "imported:", None, QtGui.QApplication.UnicodeUTF8))
        self.importedCounter.setText(QtGui.QApplication.translate("Import", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Import", "errors:", None, QtGui.QApplication.UnicodeUTF8))
        self.errorsCounter.setText(QtGui.QApplication.translate("Import", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllButton.setText(QtGui.QApplication.translate("Import", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.importCancelButton.setText(QtGui.QApplication.translate("Import", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("Import", "&Close", None, QtGui.QApplication.UnicodeUTF8))

import pydosh_rc
