
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.9'
version_full = 'c1cfa559ec90c3bf52801abb3496dcbf0c9f4aa5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

