
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.1'
version_full = '79d1cf0fa32a3785130580085199c52253723b32'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

