#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_gr` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-gr",
    version = "7.0.355",
    description = "Greece - Accounting",
    long_description = 
"""

This is the base module to manage the accounting chart for Greece.
==================================================================

Greek accounting chart and localization.
    
""",
    url = "http://openerp.hellug.gr/",
    author = "P. Christeas, OpenERP SA.",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_gr': ".",
    },
    packages = ["openerp.addons.l10n_gr"],
    package_data = {
        'openerp.addons.l10n_gr': ["i18n/*.po*","account_chart.xml","l10n_gr_wizard.xml","account_full_chart.xml","account_types.xml","account_tax_vat.xml","account_tax.xml","images/config_chart_l10n_gr.jpeg","images/l10n_gr_chart.jpeg","static/src/img/icon.png","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/pt_BR.po","i18n/es_VE.po","i18n/es_PY.po","i18n/sr@latin.po","i18n/es.po","i18n/it.po","i18n/nl.po","i18n/tr.po","i18n/de.po","i18n/hu.po","i18n/el.po","i18n/gl.po","i18n/ca.po","i18n/fr.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","account_types.xml","account_chart.xml","account_full_chart.xml","account_tax.xml","account_tax_vat.xml","l10n_gr_wizard.xml"],
    },
    install_requires = ["openerp-core","openerp-account","openerp-base-iban","openerp-base-vat","openerp-account-chart"],
    tests_require = ["unittest2"],
)
