python: 
- 2.6
- 2.7
env: 
  global: 
    secure: MvJAjdSgb9QML/pQJWJVGenq09UH0RA6COpXaRubojag+OxnRsXenV+H+HUDL58WOSF2S5lgPp6j1XtQcXDrYY+4wWeOjkDNlb2hP66n5e88EmPqtNYuDt1yC1PCkvyWxj1s3/QEShchMkWapcEazh8dx3nUgFUZOh5vBWmnMfA=
  matrix: 
  - PLONE=4.0
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3 QA=true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bin/test
after_success: test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
matrix: 
  exclude: 
  - python: 2.7
    env: PLONE=4.0
  - python: 2.7
    env: PLONE=4.1
  - python: 2.6
    env: PLONE=4.2
  - python: 2.6
    env: PLONE=4.3 QA=true
install: 
- sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg -N -q -t 10
language: python
