#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `fleet` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-fleet",
    version = "7.0.355",
    description = "Fleet Management",
    long_description = 
"""

Vehicle, leasing, insurances, cost
==================================
With this module, OpenERP helps you managing all your vehicles, the
contracts associated to those vehicle as well as services, fuel log
entries, costs and many other features necessary to the management 
of your fleet of vehicle(s)

Main Features
-------------
* Add vehicles to your fleet
* Manage contracts for vehicles
* Reminder when a contract reach its expiration date
* Add services, fuel log entry, odometer values for all vehicles
* Show all costs associated to a vehicle or to a type of service
* Analysis graph for costs
""",
    url = "http://www.openerp.com",
    author = "OpenERP S.A.",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.fleet': ".",
    },
    packages = ["openerp.addons.fleet"],
    package_data = {
        'openerp.addons.fleet': ["i18n/*.po*","fleet_cars.xml","fleet_data.xml","fleet_view.xml","fleet_board_view.xml","fleet_demo.xml","images/vehicles.jpeg","images/vehicles_services.jpeg","images/indicative_costs_analysis.jpeg","images/costs_analysis.jpeg","images/vehicles_odometer.jpeg","images/vehicles_fuel.jpeg","images/vehicles_contracts.jpeg","static/src/img/icon.png","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/cs.po","i18n/pt_BR.po","i18n/bg.po","i18n/ro.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/tr.po","i18n/de.po","i18n/lo.po","i18n/hu.po","i18n/lv.po","i18n/mk.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/ar.po","i18n/pt.po","security/ir.model.access.csv","security/fleet_security.xml","fleet_view.xml","fleet_cars.xml","fleet_data.xml","fleet_board_view.xml","fleet_demo.xml"],
    },
    install_requires = ["openerp-core","openerp-mail","openerp-board"],
    tests_require = ["unittest2"],
)
