# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './etmHelp.ui'
#
# Created: Sat Dec  7 17:35:50 2013
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(539, 349)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/etm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("font-size: 10pt")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(6, 12, 6, 6)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.overviewLayout = QtWidgets.QGridLayout(self.overviewTab)
        self.overviewLayout.setContentsMargins(0, 0, 0, 0)
        self.overviewLayout.setObjectName("overviewLayout")
        self.overviewBrowser = QtWidgets.QTextBrowser(self.overviewTab)
        self.overviewBrowser.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.overviewBrowser.setObjectName("overviewBrowser")
        self.overviewLayout.addWidget(self.overviewBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.overviewTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dataTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dataBrowser = QtWidgets.QTextBrowser(self.dataTab)
        self.dataBrowser.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dataBrowser.setObjectName("dataBrowser")
        self.gridLayout_2.addWidget(self.dataBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, "")
        self.viewsTab = QtWidgets.QWidget()
        self.viewsTab.setObjectName("viewsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.viewsTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.viewsBrowser = QtWidgets.QTextBrowser(self.viewsTab)
        self.viewsBrowser.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.viewsBrowser.setObjectName("viewsBrowser")
        self.gridLayout_3.addWidget(self.viewsBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.viewsTab, "")
        self.reportsTab = QtWidgets.QWidget()
        self.reportsTab.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.reportsTab.setObjectName("reportsTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.reportsTab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.reportsBrowser = QtWidgets.QTextBrowser(self.reportsTab)
        self.reportsBrowser.setObjectName("reportsBrowser")
        self.gridLayout_6.addWidget(self.reportsBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.reportsTab, "")
        self.shortcutsTab = QtWidgets.QWidget()
        self.shortcutsTab.setObjectName("shortcutsTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.shortcutsTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shortcutsBrowser = QtWidgets.QTextBrowser(self.shortcutsTab)
        self.shortcutsBrowser.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.shortcutsBrowser.setObjectName("shortcutsBrowser")
        self.gridLayout_4.addWidget(self.shortcutsBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.shortcutsTab, "")
        self.preferencesTab = QtWidgets.QWidget()
        self.preferencesTab.setObjectName("preferencesTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.preferencesTab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.preferencesBrowser = QtWidgets.QTextBrowser(self.preferencesTab)
        self.preferencesBrowser.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.preferencesBrowser.setObjectName("preferencesBrowser")
        self.gridLayout_5.addWidget(self.preferencesBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.preferencesTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 6)
        self.previous = QtWidgets.QToolButton(Dialog)
        self.previous.setStyleSheet("border: 0pt")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous.setIcon(icon1)
        self.previous.setIconSize(QtCore.QSize(18, 18))
        self.previous.setObjectName("previous")
        self.gridLayout.addWidget(self.previous, 1, 1, 1, 1)
        self.search = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setMinimumSize(QtCore.QSize(160, 0))
        self.search.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.search.setText("")
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 1, 2, 1, 1)
        self.next = QtWidgets.QToolButton(Dialog)
        self.next.setStyleSheet("border: 0pt")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon2)
        self.next.setIconSize(QtCore.QSize(18, 18))
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 1, 3, 1, 1)
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 1, 5, 1, 1)
        self.status_message = QtWidgets.QLineEdit(Dialog)
        self.status_message.setFocusPolicy(QtCore.Qt.NoFocus)
        self.status_message.setStyleSheet("background: transparent; border: 0pt")
        self.status_message.setObjectName("status_message")
        self.gridLayout.addWidget(self.status_message, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overviewTab), _translate("Dialog", "Overview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("Dialog", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewsTab), _translate("Dialog", "Views"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reportsTab), _translate("Dialog", "Reports"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shortcutsTab), _translate("Dialog", "Shortcuts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferencesTab), _translate("Dialog", "Preferences"))
        self.previous.setToolTip(_translate("Dialog", "Click here or press Shift-Ctrl-G to search backwards."))
        self.previous.setText(_translate("Dialog", "..."))
        self.search.setToolTip(_translate("Dialog", "Click here or press Ctrl-F to enter a search expression."))
        self.search.setPlaceholderText(_translate("Dialog", "search"))
        self.next.setToolTip(_translate("Dialog", "Click here or press Ctrl-G to search forwards."))
        self.next.setText(_translate("Dialog", "..."))
        self.closeButton.setText(_translate("Dialog", "OK"))

