// Generated by CoffeeScript 1.6.3
(function() {
  var Executor, Iteration, promiseBasedMapService, _findIterationByItem;

  promiseBasedMapService = angular.module("promiseBasedMapService", []);

  Iteration = (function() {
    function Iteration(num, item, defer, ret) {
      this.num = num;
      this.item = item;
      this.defer = defer;
      this.ret = ret;
    }

    return Iteration;

  })();

  _findIterationByItem = function(executor, item) {
    return _.find(executor.iterations, function(iteration) {
      return iteration.item === item;
    });
  };

  Executor = (function() {
    function Executor(items, func, numCalls, iter, iterations) {
      this.items = items;
      this.func = func;
      this.numCalls = numCalls;
      this.iter = iter != null ? iter : 0;
      this.iterations = iterations != null ? iterations : [];
    }

    Executor.prototype.execute = function($scope, defer) {
      this.iterations.push(new Iteration(this.iter, this.items[this.iter], defer, this.func.call($scope, this.items[this.iter], defer)));
      this.iter += 1;
      return defer.promise;
    };

    return Executor;

  })();

  promiseBasedMapService.factory("PromiseBasedMapService", function() {
    var servicer;
    return servicer = {
      executor: function(items, func, numCalls) {
        if (numCalls == null) {
          numCalls = 1;
        }
        return new Executor(items, func, numCalls);
      },
      findIterationByItem: function(executor, item) {
        return _findIterationByItem(executor, item);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=promiseBasedMapService.map
*/
