
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1'
version_full = 'd557a62db5c32035074a1085f10352486975a031'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

