#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `process` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-process",
    version = "7.0.355",
    description = "Enterprise Process",
    long_description = 
"""

This module shows the basic processes involved in the selected modules and in the sequence they occur.
======================================================================================================

**Note:** This applies to the modules containing modulename_process.xml.

**e.g.** product/process/product_process.xml.

    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.process': ".",
    },
    packages = ["openerp.addons.process"],
    package_data = {
        'openerp.addons.process': ["i18n/*.po*","process_demo.xml","process_view.xml","images/process_nodes.jpeg","images/processes.jpeg","images/process_transitions.jpeg","static/src/xml/process.xml","static/src/js/process.js","static/src/img/cta-a.gif","static/src/img/node-current.png","static/src/img/node-subflow-gray.png","static/src/img/node.png","static/src/img/button-a-a.png","static/src/img/node-gray.png","static/src/img/iconset-a-help.gif","static/src/img/node-subflow.png","i18n/sk.po","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/hi_HI.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/hi.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/es_CL.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","security/ir.model.access.csv","security/ir.model.access.csv","process_view.xml","static/src/xml/*.xml","static/src/css/process.css","static/src/js/process.js"],
    },
    install_requires = ["openerp-web"],
    tests_require = ["unittest2"],
)
