__version__ = "0.6.17"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "yalon@infinidat.com"
__git_branch__ = '(detached from v0.6.17)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd31c2de57d55e7459951f0918200bc66c10bd920'
__git_head_subject__ = 'Finished release v0.6.17.'
__git_head_message__ = ''
__git_dirty_diff__ = ''