#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_multilang` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-multilang",
    version = "7.0.355",
    description = "Multi Language Chart of Accounts",
    long_description = 
"""

    * Multi language support for Chart of Accounts, Taxes, Tax Codes, Journals,
      Accounting Templates, Analytic Chart of Accounts and Analytic Journals.
    * Setup wizard changes
        - Copy translations for COA, Tax, Tax Code and Fiscal Position from
          templates to target objects.
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_multilang': ".",
    },
    packages = ["openerp.addons.l10n_multilang"],
    package_data = {
        'openerp.addons.l10n_multilang': ["i18n/*.po*","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/pt_BR.po","i18n/ro.po","i18n/es.po","i18n/mn.po","i18n/nl.po","i18n/tr.po","i18n/de.po","i18n/hu.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po"],
    },
    install_requires = ["openerp-account-accountant"],
    tests_require = ["unittest2"],
)
