
# This file was generated by 'versioneer.py' (0.9) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.30-dirty'
version_full = '3e61a0f0e81f5c8f75f0fb27c705b1950c3ce7b8-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

