
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = 'd0949db83318d65e2f7b380351ed93e98f174262'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

