before_install:
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get update -qq || true; fi"
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get --reinstall install -qq language-pack-en-base language-pack-pl-base; fi"
language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  include:
    - python: "2.7"
      env: NMODE=flake8
env:
    NMODE=nikola
install:
  - "if [[ $NMODE == 'nikola' ]]; then pip install -r requirements-tests.txt --use-mirrors; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install . --use-mirrors; fi"
  - "if [[ $NMODE == 'flake8' ]]; then pip install flake8 --use-mirrors; fi"
# We run tests, nikola (to see if the command is executable) and flake8.
script:
  - "if [[ $NMODE == 'nikola' ]]; then nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy; fi"
  - "if [[ $NMODE == 'nikola' ]]; then nikola help; fi"
  - "if [[ $NMODE == 'flake8' ]]; then flake8 --ignore=E501 .; fi"
after_success:
  - "if [[ $NMODE == 'nikola' ]]; then coveralls; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
