
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.2'
version_full = '848a2f57c8d374cd79d7bdb0dd6d40c5567d4c43'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

