from munin_plugins.nginx_analyzers.latencyaggregator import LatencyAggregator
from munin_plugins.nginx_analyzers.botscounter import BotsCounter
from munin_plugins.nginx_analyzers.httpcodescounter import HttpCodesCounter
