#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `project_issue` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-project-issue",
    version = "7.0.355",
    description = "Issue Tracker",
    long_description = 
"""

Track Issues/Bugs Management for Projects
=========================================
This application allows you to manage the issues you might face in a project like bugs in a system, client complaints or material breakdowns. 

It allows the manager to quickly check the issues, assign them and decide on their status quickly as they evolve.
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.project_issue': ".",
    },
    packages = ["openerp.addons.project_issue","openerp.addons.project_issue.report"],
    package_data = {
        'openerp.addons.project_issue': ["i18n/*.po*","board_project_issue_view.xml","res_config_view.xml","project_issue_menu.xml","project_issue_demo.xml","project_issue_data.xml","project_issue_view.xml","images/issue_analysis.jpeg","images/project_issue.jpeg","static/src/img/icon.png","i18n/sk.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/es_VE.po","i18n/ja.po","i18n/ro.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/lt.po","i18n/hu.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/issue_process.yml","test/cancel_issue.yml","test/issue_demo.yml","test/issue.eml","test/subscribe_issue.yml","security/ir.model.access.csv","security/project_issue_security.xml","report/project_issue_report_view.xml","project_issue_view.xml","project_issue_menu.xml","report/project_issue_report_view.xml","security/project_issue_security.xml","security/ir.model.access.csv","board_project_issue_view.xml","res_config_view.xml","project_issue_data.xml","project_issue_demo.xml"],
    },
    install_requires = ["openerp-base-status","openerp-crm","openerp-project"],
    tests_require = ["unittest2"],
)
