__version__ = "0.3.12"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.12)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '667e97dd0d70eb76ace85db0bb5095288a263697'
__git_head_subject__ = 'buildout.cfg: changed isolated python version to v2.7.5.5'
__git_head_message__ = ''
__git_dirty_diff__ = ''