
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.12'
version_full = 'bd01c8a1c425348a3b4998ddf047d3ed7d437c4f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

