
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = '14c7858c79c537a024ae99a0c7b31429df2831f1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

