__version__ = "0.1.24"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.24)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '93494aa05f9523b65d7d53c2d87c3891e5f5e9b6'
__git_head_subject__ = 'Finished release v0.1.24.'
__git_head_message__ = '* release/v0.1.24:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''