#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `account_analytic_analysis` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-account-analytic-analysis",
    version = "7.0.355",
    description = "Contracts Management",
    long_description = 
"""

This module is for modifying account analytic view to show important data to project manager of services companies.
===================================================================================================================

Adds menu to show relevant information to each manager.You can also view the report of account analytic summary user-wise as well as month-wise.
""",
    url = "http://www.camptocamp.com/",
    author = "Camptocamp",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.account_analytic_analysis': ".",
    },
    packages = ["openerp.addons.account_analytic_analysis"],
    package_data = {
        'openerp.addons.account_analytic_analysis': ["i18n/*.po*","res_config_view.xml","account_analytic_analysis_cron.xml","account_analytic_analysis_view.xml","analytic_account_demo.xml","images/overpassed_accounts.jpeg","images/bill_tasks_works.jpeg","i18n/fa.po","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/gu.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/es_PY.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/oc.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","security/ir.model.access.csv","security/account_analytic_analysis_security.xml","security/ir.model.access.csv","security/account_analytic_analysis_security.xml","account_analytic_analysis_view.xml","account_analytic_analysis_cron.xml","res_config_view.xml","analytic_account_demo.xml","static/src/css/analytic.css"],
    },
    install_requires = ["openerp-hr-timesheet-invoice","openerp-sale"],
    tests_require = ["unittest2"],
)
