
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(src/python/twitter/common/python/BUILD:pex)

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'An alias to twitter.common.python and .pex standalone environments',
    'install_requires': ['twitter.common.python'],
    'license': 'Apache License, Version 2.0',
    'name': 'pex',
    'url': 'https://github.com/twitter/commons/tree/master/src/python/twitter/common/python',
    'version': '0.1.0',
    'zip_safe': True}
)
