#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `survey` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-survey",
    version = "7.0.355",
    description = "Survey",
    long_description = 
"""

This module is used for surveying.
==================================

It depends on the answers or reviews of some questions by different users. A
survey may have multiple pages. Each page may contain multiple questions and each
question may have multiple answers. Different users may give different answers of
question and according to that survey is done. Partners are also sent mails with
user name and password for the invitation of the survey.
    
""",
    url = "",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.survey': ".",
    },
    packages = ["openerp.addons.survey","openerp.addons.survey.report","openerp.addons.survey.wizard"],
    package_data = {
        'openerp.addons.survey': ["i18n/*.po*","survey_view.xml","survey_data.xml","survey_demo.xml","survey_report.xml","images/survey_pages.jpeg","images/surveys.jpeg","images/survey_answers.jpeg","specification/survey_page.png","specification/survey.png","specification/survey_question.png","specification/survey_response.png","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/bg.po","i18n/es_VE.po","i18n/ja.po","i18n/ro.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/hu.po","i18n/gl.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/draft2open2close_survey.yml","test/survey_question_type.yml","test/draft2open2close_request.yml","test/survey_report.yml","security/ir.model.access.csv","security/survey_security.xml","wizard/survey_browse_answer.xml","wizard/survey_print.xml","wizard/survey_send_invitation.xml","wizard/survey_answer.xml","wizard/survey_selection.xml","wizard/survey_print_answer.xml","wizard/survey_print_statistics.xml","survey_report.xml","survey_data.xml","wizard/survey_selection.xml","wizard/survey_answer.xml","security/survey_security.xml","security/ir.model.access.csv","survey_view.xml","wizard/survey_print_statistics.xml","wizard/survey_print_answer.xml","wizard/survey_browse_answer.xml","wizard/survey_print.xml","wizard/survey_send_invitation.xml","survey_demo.xml","static/src/css/survey.css","static/css/survey.css"],
    },
    install_requires = ["openerp-mail"],
    tests_require = ["unittest2"],
)
