
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.8'
version_full = '2ff59fcd1c1c71062a3ee89c171a213814b94dfb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

