#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `document_ftp` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-document-ftp",
    version = "7.0.355",
    description = "Shared Repositories (FTP)",
    long_description = 
"""

This is a support FTP Interface with document management system.
================================================================

With this module you would not only be able to access documents through OpenERP
but you would also be able to connect with them through the file system using the
FTP client.
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.document_ftp': ".",
    },
    packages = ["openerp.addons.document_ftp","openerp.addons.document_ftp.ftpserver","openerp.addons.document_ftp.wizard"],
    package_data = {
        'openerp.addons.document_ftp': ["i18n/*.po*","res_config_view.xml","images/1_configure_ftp.jpeg","images/2_document_browse.jpeg","images/3_document_ftp.jpeg","i18n/sk.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/bg.po","i18n/es_VE.po","i18n/es_PY.po","i18n/ja.po","i18n/ro.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/document_ftp_test2.yml","test/document_ftp_test.yml","test/document_ftp_test3.yml","test/document_ftp_test4.yml","test/document_ftp_test5.yml","security/ir.model.access.csv","wizard/ftp_browse_view.xml","wizard/ftp_configuration_view.xml","wizard/ftp_configuration_view.xml","wizard/ftp_browse_view.xml","security/ir.model.access.csv","res_config_view.xml"],
    },
    install_requires = ["openerp-core","openerp-document"],
    tests_require = ["unittest2"],
)
