options = (
    ('awstats-dir',
     {'type' : 'string',
      'default': '/var/lib/awstats',
      'help': 'directory where the files produced by awstats are stored on the filesystem. ',
      'group': 'awstats', 'level': 0,
      }),
    ('awstats-domain',
     {'type' : 'string',
      'default': '',
      'help': 'domain of the website (eg. example.org). ',
      'group': 'awstats', 'level': 0,
      }),
    ('awstats-periodicity',
     {'type' : 'choice',
      'choices' : ('hour', 'day', 'month'),
      'default': 'day',
      'help': 'stats periodicity',
      'group': 'awstats', 'level': 0,
      }),
)
