# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.fsl.epi import ApplyTOPUP
def test_ApplyTOPUP_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    datatype=dict(argstr='-d=%s',
    ),
    in_index=dict(mandatory=True,
    argstr='%s',
    ),
    args=dict(argstr='%s',
    ),
    interp=dict(argstr='--interp=%s',
    ),
    in_files=dict(mandatory=True,
    argstr='%s',
    ),
    encoding_file=dict(argstr='--datain=%s',
    mandatory=True,
    ),
    in_topup=dict(argstr='--topup=%s',
    mandatory=True,
    ),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    out_base=dict(argstr='--out=%s',
    ),
    output_type=dict(),
    method=dict(argstr='--method=%s',
    ),
    )
    inputs = ApplyTOPUP.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_ApplyTOPUP_outputs():
    output_map = dict(out_corrected=dict(),
    )
    outputs = ApplyTOPUP.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
