# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.fsl.preprocess import PRELUDE
def test_PRELUDE_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    magnitude_file=dict(mandatory=True,
    xor=['complex_phase_file'],
    argstr='--abs=%s',
    ),
    removeramps=dict(argstr='--removeramps',
    ),
    end=dict(argstr='--end=%d',
    ),
    process3d=dict(xor=['labelprocess2d', 'process2d'],
    argstr='--force3D',
    ),
    complex_phase_file=dict(mandatory=True,
    xor=['magnitude_file', 'phase_file'],
    argstr='--complex=%s',
    ),
    process2d=dict(xor=['labelprocess2d'],
    argstr='--slices',
    ),
    args=dict(argstr='%s',
    ),
    num_partitions=dict(argstr='--numphasesplit=%d',
    ),
    unwrapped_phase_file=dict(hash_files=False,
    genfile=True,
    argstr='--unwrap=%s',
    ),
    rawphase_file=dict(hash_files=False,
    argstr='--rawphase=%s',
    ),
    phase_file=dict(mandatory=True,
    xor=['complex_phase_file'],
    argstr='--phase=%s',
    ),
    threshold=dict(argstr='--thresh=%.10f',
    ),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    label_file=dict(hash_files=False,
    argstr='--labels=%s',
    ),
    savemask_file=dict(hash_files=False,
    argstr='--savemask=%s',
    ),
    mask_file=dict(argstr='--mask=%s',
    ),
    labelprocess2d=dict(argstr='--labelslices',
    ),
    output_type=dict(),
    start=dict(argstr='--start=%d',
    ),
    )
    inputs = PRELUDE.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_PRELUDE_outputs():
    output_map = dict(unwrapped_phase_file=dict(),
    )
    outputs = PRELUDE.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
