language: python
python: 2.7
install: make travis
script: make test 
notifications:
  email: guido.stevens@cosent.net
after_script:
  - kill $JAVA_PID
env:
  global:
  - secure: ! "UDvxbh56vzNdb8cGnpZ8Xy9TifIQpGqBzx9drxBohAOdmLKFhTQi9iqmZiF6\nG0+p6NDZFFBpKxBY1itPXbz/b2ByDneFS5isWkZF73qviSR9M4F2Z5RSDqVv\nPZ33nhsyrNMeS+abU25XmN/W+qfsWzl1wOujQHqmiHEWU1kPh8s="
  - secure: ! "GYlqyCo3PG+5Sc2BqceSZN2m9j0ReftHxMsREg6Iq0a4d9BeiEuTooSTrkoY\neJlQgA+t0UyokUIs/sTkdvI8GLcggvC5Fr7Y7KSzYoL5UUO4T15xFjoO3yw7\nFofAN+feMG3vmCn/9B9kmi7N6O31qImduQYZ9//AUGjibxdJ5Yc="
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
  - ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID