language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
install:
    - pip install coverage coveralls mock
script:
    - coverage run --source=check_manifest setup.py test -q
    - coverage run --append check_manifest.py
after_script:
    - coveralls
notifications:
    email: false
