__version__ = "0.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7b230b3debfaed00425a6a492ab8512411c1f892'
__git_head_subject__ = 'Finished release v0.1.'
__git_head_message__ = '* release/v0.1:\n  TRIVIAL updated bootstrap\n  TRIVIAL fixing tests\n  TRIVIAL Service.is_running()\n  TRIVIAL ServiceControlManager().is_service_exist'
__git_dirty_diff__ = ''