__version__ = "0.1.13"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2bdc68bd6613e96ca541d7cb724c7a48157cc1dd'
__git_head_subject__ = 'updated project files from skeleton'
__git_head_message__ = ''
__git_dirty_diff__ = ''