
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8'
version_full = 'fd0d19f81d7a627bdffe3ab44658928074fb5acb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

