streamcorpus_pipeline:
  log_level: INFO

  output_chunk_max_count: 10000

  ## tmp_dir, some readers and writers require this dir to be in
  ## the same file system as their output.  This is also where the
  ## batch_transforms operate.
  tmp_dir_path:  tmp

  ## generator of StreamItems
  reader: from_local_chunks

  incremental_transforms: [
    upgrade_streamcorpus_v0_3_0,
    language, 
    guess_media_type, 
    clean_html, 
    hyperlink_labels, 
    clean_visible
    ]

  batch_transforms: [serif]

  ## to_local_chunks must be last, because *moves* the tmp file away
  writers: [to_local_chunks]

  clean_html:
    require_language_code: en
    included_language_codes: ["en", ""]

  hyperlink_labels:
    require_clean_html: true
    require_abs_url: true
    all_domains: true
    offset_types: [BYTES]

  clean_visible:
    require_clean_html: true

  to_local_tarballs:
    output_path: data/kba-streamcorpus-2013-v0_3_0-clean_visible-tarballs
    output_name: "%(date_hour)s/%(source)s-%(num)d-%(input_md5)s-%(md5)s"

  to_local_chunks:
    output_type: otherdir
    output_path: cyber1/
    output_name: "cyber-tagged-by-serif-%(first)s-%(num)s"

  serif:
    pipeline_root_path: /third/serif/serif-2013-12-16
    cleanup_tmp_files: true
    par: streamcorpus_one_step
