__version__ = "0.3.21"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.21)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cce4cff8efb5b5406e6f16b2fa9e246e70f14eb0'
__git_head_subject__ = 'STORAGEMODEL-255 EUI64_16Byte_Designator.identifier_extension is 8 bytes'
__git_head_message__ = ''
__git_dirty_diff__ = ''