--- !ditz.rubyforge.org,2008-03-06/project 
name: PyDitz
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: PyDitz
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2013-11-23 00:10:48.045971 Z
  log_events: 
  - - 2010-04-09 14:35:19.190619 Z
    - Glenn Hutchings <zondo42@googlemail.com>
    - created
    - ""
  - - 2013-11-23 00:10:48.046045 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - It's good to go.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2013-11-23 16:32:01.769636 Z
  log_events: 
  - - 2013-11-23 16:19:36.052722 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - Typical... just after release, then the bugs appear.
  - - 2013-11-23 16:32:01.769712 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - Let's try again...
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2013-11-23 22:54:28.305275 Z
  log_events: 
  - - 2013-11-23 21:15:49.429777 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - More bugs to fix...
  - - 2013-11-23 22:54:28.305348 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :released
  release_time: 2013-12-09 19:10:58.456029 Z
  log_events: 
  - - 2013-12-01 15:48:02.236282 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
  - - 2013-12-09 19:10:58.456039 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-12-09 19:14:18.575684 Z
    - Glenn Hutchings <zondo42@gmail.com>
    - created
    - ""
