#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `project_timesheet` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-project-timesheet",
    version = "7.0.355",
    description = "Bill Time on Tasks",
    long_description = 
"""

Synchronization of project task work entries with timesheet entries.
====================================================================

This module lets you transfer the entries under tasks defined for Project
Management to the Timesheet line entries for particular date and particular user
with the effect of creating, editing and deleting either ways.
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.project_timesheet': ".",
    },
    packages = ["openerp.addons.project_timesheet","openerp.addons.project_timesheet.report"],
    package_data = {
        'openerp.addons.project_timesheet': ["i18n/*.po*","project_timesheet_demo.xml","project_timesheet_view.xml","images/invoice_task_work.jpeg","images/my_timesheet.jpeg","images/working_hour.jpeg","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/work_timesheet.yml","test/worktask_entry_to_timesheetline_entry.yml","security/ir.model.access.csv","security/project_timesheet_security.xml","report/task_report_view.xml","process/project_timesheet_process.xml","security/ir.model.access.csv","security/project_timesheet_security.xml","process/project_timesheet_process.xml","report/task_report_view.xml","project_timesheet_view.xml","project_timesheet_demo.xml"],
    },
    install_requires = ["openerp-project","openerp-hr-timesheet-sheet","openerp-hr-timesheet-invoice","openerp-account-analytic-analysis"],
    tests_require = ["unittest2"],
)
