__version__ = "0.1.23"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1.23)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ba7c215d08ad9333a96a88d2845c5a8eee837cc0'
__git_head_subject__ = 'update buildout.cfg'
__git_head_message__ = ''
__git_dirty_diff__ = ''