#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_be_invoice_bba` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-be-invoice-bba",
    version = "7.0.355",
    description = "Belgium - Structured Communication",
    long_description = 
"""

    
Belgian localization for in- and outgoing invoices (prereq to account_coda):
============================================================================
    - Rename 'reference' field labels to 'Communication'
    - Add support for Belgian Structured Communication

A Structured Communication can be generated automatically on outgoing invoices according to the following algorithms:
---------------------------------------------------------------------------------------------------------------------
    1) Random : +++RRR/RRRR/RRRDD+++
        **R..R =** Random Digits, **DD =** Check Digits
    2) Date : +++DOY/YEAR/SSSDD+++
        **DOY =** Day of the Year, **SSS =** Sequence Number, **DD =** Check Digits
    3) Customer Reference +++RRR/RRRR/SSSDDD+++
        **R..R =** Customer Reference without non-numeric characters, **SSS =** Sequence Number, **DD =** Check Digits  
        
The preferred type of Structured Communication and associated Algorithm can be
specified on the Partner records. A 'random' Structured Communication will
generated if no algorithm is specified on the Partner record. 

    
""",
    url = "",
    author = "Noviat",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_be_invoice_bba': ".",
    },
    packages = ["openerp.addons.l10n_be_invoice_bba"],
    package_data = {
        'openerp.addons.l10n_be_invoice_bba': ["i18n/*.po*","account_invoice_view.xml","partner_view.xml","i18n/sl.po","i18n/pt_BR.po","i18n/sr@latin.po","i18n/es.po","i18n/nl.po","i18n/tr.po","i18n/fr.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","partner_view.xml","account_invoice_view.xml"],
    },
    install_requires = ["openerp-account"],
    tests_require = ["unittest2"],
)
