__version__ = "0.1.3"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ff9be7ad27778e9ea68769b575f1384ca0cfc21f'
__git_head_subject__ = 'Finished release v0.1.3.'
__git_head_message__ = ''
__git_dirty_diff__ = ''