
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.7'
version_full = '75309e8bd6b762cad41eaf7d6bf8d4a3696105d2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

