__version__ = "0.4.21"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.4.21)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '70b9b192047d2cdea42324b4b6169e2e89b5a3ca'
__git_head_subject__ = 'Finished release v0.4.21.'
__git_head_message__ = ''
__git_dirty_diff__ = ''