language: python
python: "2.7"
install:
  - virtualenv buildout
  - buildout/bin/pip install -U distribute
  - mkdir -p buildout-cache/downloads
  - buildout/bin/python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export ROBOT_HTTP_PORT=55001"
script: bin/test
