
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.2'
version_full = '1817e58dcb57c5fedf9870c51e711d93b88d9ec1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

