
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2'
version_full = '1a8f3ba1409b9c02a204629f3b83881a86a37b06'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

