#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `account_followup` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-account-followup",
    version = "7.0.355",
    description = "Payment Follow-up Management",
    long_description = 
"""

Module to automate letters for unpaid invoices, with multi-level recalls.
=========================================================================

You can define your multiple levels of recall through the menu:
---------------------------------------------------------------
    Configuration / Follow-Up Levels
    
Once it is defined, you can automatically print recalls every day through simply clicking on the menu:
------------------------------------------------------------------------------------------------------
    Payment Follow-Up / Send Email and letters

It will generate a PDF / send emails / set manual actions according to the the different levels 
of recall defined. You can define different policies for different companies. 

Note that if you want to check the follow-up level for a given partner/account entry, you can do from in the menu:
------------------------------------------------------------------------------------------------------------------
    Reporting / Accounting / **Follow-ups Analysis

""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.account_followup': ".",
    },
    packages = ["openerp.addons.account_followup","openerp.addons.account_followup.tests","openerp.addons.account_followup.report","openerp.addons.account_followup.wizard"],
    package_data = {
        'openerp.addons.account_followup': ["i18n/*.po*","account_followup_customers.xml","account_followup_demo.xml","account_followup_data.xml","account_followup_view.xml","images/follow_ups.jpeg","images/send_followups.jpeg","i18n/fa.po","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/es_PY.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/oc.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/account_followup.yml","security/ir.model.access.csv","security/account_followup_security.xml","report/account_followup_report.xml","report/account_followup_print.rml","report/account_followup_print.sxw","wizard/account_followup_print_view.xml","security/account_followup_security.xml","security/ir.model.access.csv","report/account_followup_report.xml","account_followup_data.xml","account_followup_view.xml","account_followup_customers.xml","wizard/account_followup_print_view.xml","account_followup_demo.xml"],
    },
    install_requires = ["openerp-account-accountant","openerp-mail"],
    tests_require = ["unittest2"],
)
