language: python
python: 3.3
env:
- TOX_ENV=py33
- TOX_ENV=flake8
install:
- pip install tox
script:
- tox -e $TOX_ENV
notifications:
  irc: chat.freenode.net#python-home
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database test_home;' -U postgres
