# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.afni.preprocess import TStat
def test_TStat_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(name_source='in_file',
    argstr='-prefix %s',
    name_template='%s_tstat',
    ),
    args=dict(argstr='%s',
    ),
    mask=dict(argstr='-mask %s',
    ),
    outputtype=dict(),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(copyfile=False,
    mandatory=True,
    position=-1,
    argstr='%s',
    ),
    options=dict(argstr='%s',
    ),
    )
    inputs = TStat.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_TStat_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = TStat.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
