__version__ = "0.0.8"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.0.8)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '49e21b1d3c4da5ce8575cf36cf468e2d18dbcdec'
__git_head_subject__ = 'Finished release v0.0.8.'
__git_head_message__ = '* release/v0.0.8:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''