__version__ = "0.6.13"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.6.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f983509c914c68c33c8c8cac90076e671597e483'
__git_head_subject__ = 'Finished release v0.6.13.'
__git_head_message__ = ''
__git_dirty_diff__ = ''