
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.9-1-gc1f9c92'
version_full = 'c1f9c92d948fc41a44010ba4dc9c5865c7455c2e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

