
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.0'
version_full = 'ce22976cc0e203e53799e771aa5e3717d498cc5c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

