__version__ = "0.1.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '09f09adf536e5dc26bbe18c890ce4b2f8872f319'
__git_head_subject__ = 'TRIVIAL handling weird Ubuntu machines that do not have ctypes.get_errno'
__git_head_message__ = ''
__git_dirty_diff__ = ''