#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_be_hr_payroll` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-be-hr-payroll",
    version = "7.0.355",
    description = "Belgium - Payroll",
    long_description = 
"""

Belgian Payroll Rules.
======================

    * Employee Details
    * Employee Contracts
    * Passport based Contract
    * Allowances/Deductions
    * Allow to configure Basic/Gross/Net Salary
    * Employee Payslip
    * Monthly Payroll Register
    * Integrated with Holiday Management
    * Salary Maj, ONSS, Withholding Tax, Child Allowance, ...
    
""",
    url = "",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_be_hr_payroll': ".",
    },
    packages = ["openerp.addons.l10n_be_hr_payroll"],
    package_data = {
        'openerp.addons.l10n_be_hr_payroll': ["i18n/*.po*","l10n_be_hr_payroll_view.xml","l10n_be_hr_payroll_data.xml","l10n_be_hr_payroll_demo.xml","data/hr.salary.rule.csv","static/src/img/icon.png","i18n/sl.po","i18n/pt_BR.po","i18n/sr@latin.po","i18n/es.po","i18n/nl.po","i18n/tr.po","i18n/de.po","i18n/zh_CN.po","i18n/pt.po","i18n/es_CR.po","l10n_be_hr_payroll_view.xml","l10n_be_hr_payroll_data.xml","data/hr.salary.rule.csv","l10n_be_hr_payroll_demo.xml"],
    },
    install_requires = ["openerp-hr-payroll"],
    tests_require = ["unittest2"],
)
