
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.6'
version_full = '25ef3a640bb6e7877487a6300c065635092c92c0'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

