
# This file was generated by 'versioneer.py' (0.9) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.2-2-g093d800-dirty'
version_full = '093d8009b56ea3286f2bd89644d45ac161114d07-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

