#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_ro` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-ro",
    version = "7.0.355",
    description = "Romania - Accounting",
    long_description = 
"""

This is the module to manage the accounting chart, VAT structure and Registration Number for Romania in OpenERP.
================================================================================================================

Romanian accounting chart and localization.
    
""",
    url = "http://www.erpsystems.ro",
    author = "TOTAL PC SYSTEMS",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_ro': ".",
    },
    packages = ["openerp.addons.l10n_ro"],
    package_data = {
        'openerp.addons.l10n_ro': ["i18n/*.po*","account_tax_code_template.xml","account_chart.xml","partner_view.xml","l10n_chart_ro_wizard.xml","account_tax_template.xml","images/config_chart_l10n_ro.jpeg","images/l10n_ro_chart.jpeg","static/src/img/icon.png"],
    },
    install_requires = ["openerp-account","openerp-account-chart","openerp-base-vat"],
    tests_require = ["unittest2"],
)
