# -*- coding: utf-8 -*-

names = (
u'nk_m',
u'fhollande',
u'benoithamon',
u'EELV',
u'elysee',
u'laurentwauquiez',
u'cecileduflot',
u'MartineAubry',
u'montebourg',
u'Anne_Hidalgo',
u'vpecresse',
#u'Eric_Besson',
u'RoyalSegolene',
u'bayrou',
u'evajoly',
u'jf_cope',
u'partisocialiste',
u'villepin',
u'danycohnbendit',
u'MLP_officiel',
u'jlborloo',
u'ump',
u'pierremoscovici',
u'chevenement',
u'ManuelValls',
u'jeanmarcayrault',
u'FLefebvre_UMP',
u'Herve_Morin',
u'francoisbaroin',
u'lancarbenjamin',
u'corinnelepage',
u'lucchatel',
u'christineboutin',
u'Melenchon2012',
u'laurentfabius',
u'dupontaignan',
u'harlemdesir',
u'ch_estrosi',
u'benoistapparu',
u'juppealain',
u'Michelbarnier',
u'najatvb',
u'juliendray',
u'josebove',
u'frebsamen',
u'modem',
u'Fdebeauce',
u'yvesjego',
u'xavierbertrand',
u'jpraffarin',
u'FN_officiel',
u'DominiquePaille',
u'Dbussereau',
u'RHammadi',
u'aurelifil',
u'ThierryMARIANI',
u'DDouillet',
u'datirachida',
u'mamontchamp',
u'JMBaylet',
u'Bruno_LeMaire',
u'BerraNora',
u'Besancenot',
u'MAlliotMarie',
u'XavierDarcos',
u'pDevedjian',
u'Sauvadet',
u'mlebranchu',
u'SLeFoll',
u'jeanlassalle')

list_rss = []
for name in names:
    list_rss.append((u'Twitter - %s' % name, name, u'fr'))


for (name, url, lang) in list_rss:
    session.create_entity('CWSource', name=name, type=u'datafeed',
                          parser=u'tweet-parser', lang=lang, url=url,
                          config=u'synchronization-interval=120min')
