language: python
python:
  - 2.7
  - 3.3
install: pip install -r test-requirements.txt -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=rcbu tests/unit
after_success:
  - coveralls
