__version__ = "0.3.34"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.3.34)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8a16970680c21f81d6ec8723e83836c3bda00ff6'
__git_head_subject__ = 'Finished release v0.3.34.'
__git_head_message__ = '* release/v0.3.34:\n  fix tests\n  HIP-783 add windows 2012 r2 to application_packager\n  fix tests'
__git_dirty_diff__ = ''