#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `l10n_ch` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-l10n-ch",
    version = "7.0.355",
    description = "Switzerland - Accounting",
    long_description = 
"""

Swiss localization
==================
 **Multilang swiss STERCHI account chart and taxes**
  **Author:** Camptocamp SA

  **Financial contributors:** Prisme Solutions Informatique SA, Quod SA

  **Translation contributors:** brain-tec AG, Agile Business Group

 **This release will introduce major changes to l10n_ch.**

 Due to important refactoring needs and the Switzerland adoption of new international payment standard during 2013-2014. We have reorganised the swiss localization addons this way:

 - **l10n_ch**: Multilang swiss STERCHI account chart and taxes (official addon)
 - **l10n_ch_base_bank**: Technical module that introduces a new and simplified version of bank type management
 - **l10n_ch_bank**: List of swiss banks
 - **l10n_ch_zip**: List of swiss postal zip
 - **l10n_ch_dta**: Support of dta payment protocol (will be deprecated end 2014)
 - **l10n_ch_payment_slip**: Support of ESR/BVR payment slip report and reconciliation. Report refactored with easy element positioning.
 - **l10n_ch_sepa**: Alpha implementation of PostFinance SEPA/PAIN support will be completed during 2013/2014

 The modules will be soon available on OpenERP swiss localization on launchpad:
 https://launchpad.net/openerp-swiss-localization
""",
    url = "http://www.camptocamp.com",
    author = "Camptocamp",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.l10n_ch': ".",
    },
    packages = ["openerp.addons.l10n_ch"],
    package_data = {
        'openerp.addons.l10n_ch': ["i18n/*.po*","wizard.xml","images/l10n_ch_chart.jpeg","images/config_chart_l10n_ch.jpeg","static/src/img/icon.png","i18n/it.po","i18n/de.po","sterchi_chart/fiscal_position.xml","sterchi_chart/vat2011.xml","sterchi_chart/account.xml","sterchi_chart/account.xml","sterchi_chart/vat2011.xml","sterchi_chart/fiscal_position.xml"],
    },
    install_requires = ["openerp-account","openerp-l10n-multilang"],
    tests_require = ["unittest2"],
)
