__version__ = "0.1.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7f20985d57cc702c405a69da27aea89b21cded4e'
__git_head_subject__ = 'Finished release v0.1.6.'
__git_head_message__ = '* release/v0.1.6:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''