#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `account_bank_statement_extensions` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-account-bank-statement-extensions",
    version = "7.0.355",
    description = "Bank Statement Extensions to Support e-banking",
    long_description = 
"""

Module that extends the standard account_bank_statement_line object for improved e-banking support.
===================================================================================================

This module adds:
-----------------
    - valuta date
    - batch payments
    - traceability of changes to bank statement lines
    - bank statement line views
    - bank statements balances report
    - performance improvements for digital import of bank statement (via 
      'ebanking_import' context flag)
    - name_search on res.partner.bank enhanced to allow search on bank 
      and iban account numbers
    
""",
    url = "",
    author = "Noviat",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.account_bank_statement_extensions': ".",
    },
    packages = ["openerp.addons.account_bank_statement_extensions","openerp.addons.account_bank_statement_extensions.report","openerp.addons.account_bank_statement_extensions.wizard"],
    package_data = {
        'openerp.addons.account_bank_statement_extensions': ["i18n/*.po*","account_bank_statement_report.xml","account_bank_statement_view.xml","data/account_bank_statement_extensions_data.xml","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/gu.po","i18n/ja.po","i18n/ro.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/hu.po","i18n/mk.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","security/ir.model.access.csv","report/bank_statement_balance_report.rml","wizard/cancel_statement_line_wizard.xml","wizard/confirm_statement_line_wizard.xml","security/ir.model.access.csv","account_bank_statement_view.xml","account_bank_statement_report.xml","wizard/confirm_statement_line_wizard.xml","wizard/cancel_statement_line_wizard.xml","data/account_bank_statement_extensions_data.xml"],
    },
    install_requires = ["openerp-account"],
    tests_require = ["unittest2"],
)
