# YAML kba.pipeline config for generating clean_visible and then
## operating lingpipe

streamcorpus_pipeline:
  ## root path for all things that are called *_path in this file and
  ## are not an absolute path, i.e. start with '/'
  root_path: 

  ## pipeline expects strings over stdin, which are typically paths to
  ## streamcorpus.Chunk files.  They can also be some other kind of
  ## opaque byte strings delimited by newlines that your particular
  ## 'extractor' is expecting.

  ## put logs inside each chunk file
  embedded_logs: true

  log_level: DEBUG

  output_chunk_max_count: 197

  ## the main pipeline log_dir_path can trigger similar log chunk
  log_dir_path: data/john-smith/

  ## tmp_dir_path, some extractors and loaders require this dir to be in
  ## the same file system as their output.  This is also where the
  ## batch_transforms operate.
  tmp_dir_path: tmp

  ## task_queue specifies the strings that are passed to an extractor
  ## to obtain a Chunk.  The strings might be paths in a file system
  ## or some other source of data.  The task_queue might simply be
  ## stdin, or it might be a more sophisticated shared queue.
  task_queue: stdin

  ## generator of StreamItems
  extractor: john_smith

  incremental_transforms: []

  batch_transforms: [lingpipe]

  loaders: [to_local_chunks]

  to_local_chunks:
    #output_type: inplace
    output_type: otherdir
    output_path: data/john-smith/
    output_name: "john-smith-tagged-by-lingpipe-%(first)s-prebuild"

  lingpipe:
    exit_code_on_out_of_memory: 1
    pipeline_root_path: third
    offset_types: [BYTES]
    offset_debugging: false
    cleanup_tmp_files: false

    ## convert all doc-level Rating objects into Label objects on all
    ## Tokens that appear in a coref chain that meets the criterion
    align_labels_by: names_in_chains
    aligner_data:
      ## apply Label to each Token in any chain for which ALL|ANY of
      ## the strings in Rating.mentions appear as substrings in at
      ## least one Token.token string of the coref chain
      chain_selector:  ALL
      ## identifier of annotator to find in the doc-level Ratings
      annotator_id: bagga-and-baldwin
