#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `account_asset` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-account-asset",
    version = "7.0.355",
    description = "Assets Management",
    long_description = 
"""

Financial and accounting asset management.
==========================================

This Module manages the assets owned by a company or an individual. It will keep 
track of depreciation's occurred on those assets. And it allows to create Move's 
of the depreciation lines.

    
""",
    url = "http://www.openerp.com",
    author = "OpenERP S.A.",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.account_asset': ".",
    },
    packages = ["openerp.addons.account_asset","openerp.addons.account_asset.report","openerp.addons.account_asset.wizard"],
    package_data = {
        'openerp.addons.account_asset': ["i18n/*.po*","account_asset_invoice_view.xml","account_asset_view.xml","account_asset_demo.xml","static/src/img/icon.png","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/gu.po","i18n/fr_BE.po","i18n/es_VE.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/th.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/account_asset_wizard.yml","test/account_asset_demo.yml","test/account_asset.yml","security/ir.model.access.csv","security/account_asset_security.xml","report/account_asset_report_view.xml","wizard/wizard_asset_compute_view.xml","wizard/account_asset_change_duration_view.xml","security/account_asset_security.xml","security/ir.model.access.csv","wizard/account_asset_change_duration_view.xml","wizard/wizard_asset_compute_view.xml","account_asset_view.xml","account_asset_invoice_view.xml","report/account_asset_report_view.xml","account_asset_demo.xml"],
    },
    install_requires = ["openerp-account"],
    tests_require = ["unittest2"],
)
