
# This file was generated by 'versioneer.py' (0.10+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

versions = {'closest_tag': '0.3.5', 'default': '0.3.5', 'long': '0.3.5-0-ged730eb', 'distance': 0, 'dash_dirty': '', 'describe': '0.3.5', 'short_revisionid': 'ed730eb', 'full_revisionid': 'ed730eb73aebbbf0dd2d3e7a84ca6f10d7994bac', 'pep440': '0.3.5', 'closest_tag_or_zero': '0.3.5', 'dirty': False, 'dash_distance': ''}


def get_versions(default={}, verbose=False):
    return versions
def get_version():
    return version_string_template % versions
