__version__ = "0.2.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8524f38597ffd48b05906050a62ac1548759b5bd'
__git_head_subject__ = 'Finished release v0.2.1.'
__git_head_message__ = '* release/v0.2.1:\n  HIP-924 raising PartedNotInstalledException when parted is not installed\n  TRIVIAL updated checkout instructions in README.md\n  updated project files from skeleton\n  buildout.cfg: changed isolated python version to v2.7.5.5\n  TRIVIAL gitignore\n  TRIVIAL gitignore\n  TRIVIAL gitignore\n  add description'
__git_dirty_diff__ = ''