__version__ = "0.1.6"
__git_commiter_name__ = "Tomer g"
__git_commiter_email__ = "tomerg@tomers-air.infinidat.com"
__git_branch__ = '(detached from v0.1.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '9ca61f9ad7b3f4c46eee25fc8f2755a2db4d6fc2'
__git_head_subject__ = 'Replace bunch with munch'
__git_head_message__ = ''
__git_dirty_diff__ = ''