__version__ = "0.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7e67e91495cdbd4f524efa808197a6e532548fc3'
__git_head_subject__ = 'Finished release v0.1.'
__git_head_message__ = '* release/v0.1:\n  buildout.cfg: changed isolated python version to v2.7.5.4\n  updated project files from skeleton\n  Fixed python2.6 & python3 compatability\n  TRIVIAL updated README.md'
__git_dirty_diff__ = ''