before_install:
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get update -qq || true; fi"
  - "if [[ $NMODE == 'nikola' ]]; then sudo apt-get --reinstall install -qq language-pack-en-base language-pack-pl-base; fi"
  - "pip install --upgrade pip wheel"
language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  include:
    - python: "2.7"
      env: NMODE=flake8
env:
    NMODE=nikola
install:
  - "if [[ $NMODE == 'nikola' ]]; then wget https://github.com/getnikola/wheelhouse/archive/$(scripts/getpyver.py).zip; fi"
  - "if [[ $NMODE == 'nikola' ]]; then unzip $(scripts/getpyver.py).zip; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install --use-wheel --no-index --find-links=wheelhouse-$(scripts/getpyver.py short) lxml Pillow ipython; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install -r requirements-tests.txt; fi"
  - "if [[ $NMODE == 'nikola' ]]; then pip install .; fi"
  - "if [[ $NMODE == 'flake8' ]]; then pip install flake8; fi"
# We run tests and nikola (to see if the command is executable) OR flake8.
script:
  - "if [[ $NMODE == 'nikola' ]]; then nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy; fi"
  - "if [[ $NMODE == 'nikola' ]]; then nikola help; fi"
  - "if [[ $NMODE == 'flake8' ]]; then flake8 .; fi"
after_success:
  - "if [[ $NMODE == 'nikola' ]]; then coveralls; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
