__version__ = "0.4.15"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.15)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '19e235fe699145cf0e9d6d190c4370432797b666'
__git_head_subject__ = 'Finished release v0.4.15.'
__git_head_message__ = '* release/v0.4.15:\n  fixing tests\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''