
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.13.10'
version_full = 'f04b90b126562763a957f144a0c18977e106982e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

