// File: module.v
// Generated by MyHDL 0.8.1
// Date: Fri Sep 20 18:38:28 2013


`timescale 1ns/10ps

module module (
    sigin,
    sigout
);


input [3:0] sigin;
output [3:0] sigout;
reg [3:0] sigout;






always @(sigin) begin: MODULE_OUTPUT
    reg [2-1:0] tmp;
    sigout = {sigin[0], sigin[2]};
    tmp = {sigin[0], sigin[2]};
    sigout = tmp;
end

endmodule
