__version__ = "0.1.13"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4079b40d31e916dcab70b7dd864a3f94adb57c2b'
__git_head_subject__ = 'Finished release v0.1.13.'
__git_head_message__ = '* release/v0.1.13:\n  fixing tests\n  handling ext4 quicks in Redhat6\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''