
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1'
version_full = 'c5f9f57b3013b87c564ff5974a95c16a7e3f0848'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

