language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo -u postgres createdb --owner=$USER zope_sqlalchemy_tests
  - pip install -U setuptools
install:
  - python bootstrap.py
  - bin/buildout -c postgres.cfg
script:
  - bin/test
  - bin/testpg
