victoria:
  binaries: {vasp_53: /usr/local/bin/vasp_53, vasp_53_serial: /usr/local/bin/vasp_53_serial}
  check_queue: /usr/local/maui/bin/showq
  hostname: victoria.northwestern.edu
  ip_address: 165.124.29.204
  nodes: 30
  ppn: 4
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 691200

byrd:
  binaries: {vasp_53: /usr/local/bin/vasp_53, vasp_53_serial: /usr/local/bin/vasp_53_serial}
  check_queue: /usr/local/maui/bin/showq
  hostname: byrd.northwestern.edu
  ip_address: 165.124.29.202
  nodes: 30
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400

hopper:
  binaries: {vasp_53: /global/homes/k/kylemich/share/bin/vasp.5.3.3, vasp_53_serial: /fake/path/here}
  check_queue: /opt/moab/6.1.8/bin/showq
  hostname: hopper.nersc.gov
  ip_address: 128.55.68.100
  nodes: 1000
  ppn: 24
  sub_text: local
  sub_script: /usr/common/nsg/bin/qsub
  sub_text: hopper
  walltime: 1152

josquin:
  binaries: {vasp_53: /usr/local/bin/vasp_53, vasp_53_serial: /usr/local/bin/vasp_53_serial}
  check_queue: /usr/local/maui/bin/showq
  hostname: josquin.northwestern.edu
  ip_address: 165.124.29.200
  nodes: 30
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400

palestrina:
  binaries: {vasp_53: /usr/local/bin/vasp_53, vasp_53_serial: /usr/local/bin/vasp_53_serial}
  check_queue: /usr/local/maui/bin/showq
  hostname: palestrina.northwestern.edu
  ip_address: 129.105.61.89
  nodes: 30
  ppn: 8
  sub_script: /usr/local/bin/qsub
  sub_text: local
  walltime: 1382400

quest:
  binaries: {vasp_53: /projects/b1004/bin/vasp_53, vasp_53_serial: /projects/b1004/bin/vasp_53_serial}
  check_queue: /opt/moab7/bin/showq
  hostname: quest.it.northwestern.edu
  ip_address: 165.124.130.6
  nodes: 50
  ppn: 8
  sub_script: /opt/moab7/bin/msub
  sub_text: quest
  walltime: 172800
