language: python
env:
  - TOXENV=py26-1.4.x
  - TOXENV=py26-1.5.x
  - TOXENV=py26-1.6.x
  - TOXENV=py27-1.4.x
  - TOXENV=py27-1.5.x
  - TOXENV=py27-1.6.x
  - TOXENV=py27-1.7.x
  - TOXENV=py32-1.5.x
  - TOXENV=py32-1.6.x
  - TOXENV=py32-1.7.x
  - TOXENV=py33-1.5.x
  - TOXENV=py33-1.6.x
  - TOXENV=py33-1.7.x
  - TOXENV=pypy-1.4.x
  - TOXENV=pypy-1.5.x
  - TOXENV=pypy-1.6.x
  - TOXENV=pypy-1.7.x
  - TOXENV=flake827
  - TOXENV=flake833
install:
  - pip install tox
script:
  - tox
branches:
  except:
    templates/1.5.x
    templates/1.6.x
