#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `web_analytics` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-web-analytics",
    version = "7.0.355",
    description = "Google Analytics",
    long_description = 
"""

Google Analytics.
=================

Collects web application usage with Google Analytics.
    
""",
    url = "http://openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.web_analytics': ".",
    },
    packages = ["openerp.addons.web_analytics"],
    package_data = {
        'openerp.addons.web_analytics': ["i18n/*.po*","static/src/js/web_analytics.js","static/src/img/icon.png","static/src/js/web_analytics.js"],
    },
    install_requires = ["openerp-web"],
    tests_require = ["unittest2"],
)
