__version__ = "0.0.9"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.0.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '3f8160e6134f499f15c37f65f52e982c86aeff1d'
__git_head_subject__ = 'update dependencies'
__git_head_message__ = ''
__git_dirty_diff__ = ''