# Cluster Settings
cluster:
  name: p01_elasticsearch_testing

network: 
    host: localhost

http:
  port: 45299-45300

transport:
  tcp:
    port: 45399-45400

thrift:
  port: 45500-45600

index:
  store:
    type: memory
