__version__ = "0.4.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ce0ce0a19debbd7996ce2ada4ab224cd094b702f'
__git_head_subject__ = 'TRIVIAL updated checkout instructions in README.md'
__git_head_message__ = ''
__git_dirty_diff__ = ''