
class ReturnCodes(object):
	REQUEST_SUCCESS = 0
	SERVER_SIDE_ERROR = 1
	INVALID_ZWSID = 2
	SERVICE_UNAVAILABLE = 3
	INVALID_ZPID = 500
	INVALID_COUNT = 501
	NO_RECORD = 502
	NO_ZESTIMATE = 503
	NO_RESULTS = 504