# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './etmView.ui'
#
# Created: Fri Jan  3 15:39:47 2014
#      by: PyQt5 UI code generator 5.2-snapshot-5b7a6055d52e
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_uiMainWindow(object):
    def setupUi(self, uiMainWindow):
        uiMainWindow.setObjectName("uiMainWindow")
        uiMainWindow.resize(460, 240)
        uiMainWindow.setMinimumSize(QtCore.QSize(460, 240))
        uiMainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        uiMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/etm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        uiMainWindow.setWindowIcon(icon)
        uiMainWindow.setStyleSheet("font-size: 13pt")
        uiMainWindow.setIconSize(QtCore.QSize(36, 36))
        uiMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.uiCentralWidget = QtWidgets.QWidget(uiMainWindow)
        self.uiCentralWidget.setObjectName("uiCentralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.uiCentralWidget)
        self.gridLayout.setContentsMargins(8, 6, 8, 6)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBar = QtWidgets.QHBoxLayout()
        self.toolBar.setSpacing(-1)
        self.toolBar.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.toolBar.setObjectName("toolBar")
        self.uiView = QtWidgets.QComboBox(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiView.sizePolicy().hasHeightForWidth())
        self.uiView.setSizePolicy(sizePolicy)
        self.uiView.setBaseSize(QtCore.QSize(0, 6))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.uiView.setFont(font)
        self.uiView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.uiView.setAutoFillBackground(False)
        self.uiView.setStyleSheet("")
        self.uiView.setIconSize(QtCore.QSize(24, 24))
        self.uiView.setFrame(False)
        self.uiView.setObjectName("uiView")
        self.toolBar.addWidget(self.uiView)
        self.newItemButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.newItemButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newItemButton.setStyleSheet("border: 0px solid black")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/editadd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newItemButton.setIcon(icon1)
        self.newItemButton.setIconSize(QtCore.QSize(26, 26))
        self.newItemButton.setObjectName("newItemButton")
        self.toolBar.addWidget(self.newItemButton)
        self.newActionButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.newActionButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.newActionButton.setStyleSheet("border: 0px solid black")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/action_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newActionButton.setIcon(icon2)
        self.newActionButton.setIconSize(QtCore.QSize(26, 26))
        self.newActionButton.setObjectName("newActionButton")
        self.toolBar.addWidget(self.newActionButton)
        self.reportButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.reportButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reportButton.setStyleSheet("border: 0px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportButton.setIcon(icon3)
        self.reportButton.setIconSize(QtCore.QSize(24, 26))
        self.reportButton.setObjectName("reportButton")
        self.toolBar.addWidget(self.reportButton)
        self.uiFilter = QtWidgets.QLineEdit(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiFilter.sizePolicy().hasHeightForWidth())
        self.uiFilter.setSizePolicy(sizePolicy)
        self.uiFilter.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.uiFilter.setFont(font)
        self.uiFilter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.uiFilter.setStatusTip("")
        self.uiFilter.setStyleSheet("")
        self.uiFilter.setInputMethodHints(QtCore.Qt.ImhNone)
        self.uiFilter.setText("")
        self.uiFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uiFilter.setObjectName("uiFilter")
        self.toolBar.addWidget(self.uiFilter)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolBar.addItem(spacerItem)
        self.mainHelpButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.mainHelpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mainHelpButton.setStyleSheet("border: 0px solid black")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainHelpButton.setIcon(icon4)
        self.mainHelpButton.setIconSize(QtCore.QSize(20, 20))
        self.mainHelpButton.setObjectName("mainHelpButton")
        self.toolBar.addWidget(self.mainHelpButton)
        self.toolBar.setStretch(4, 1)
        self.gridLayout.addLayout(self.toolBar, 0, 0, 1, 1)
        self.statusBar = QtWidgets.QGridLayout()
        self.statusBar.setObjectName("statusBar")
        self.alertsButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.alertsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alertsButton.setStyleSheet("border: 0px solid black")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alertsButton.setIcon(icon5)
        self.alertsButton.setIconSize(QtCore.QSize(22, 22))
        self.alertsButton.setObjectName("alertsButton")
        self.statusBar.addWidget(self.alertsButton, 0, 10, 1, 1)
        self.currentTime = QtWidgets.QLabel(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTime.sizePolicy().hasHeightForWidth())
        self.currentTime.setSizePolicy(sizePolicy)
        self.currentTime.setBaseSize(QtCore.QSize(12, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.currentTime.setFont(font)
        self.currentTime.setStyleSheet("")
        self.currentTime.setObjectName("currentTime")
        self.statusBar.addWidget(self.currentTime, 0, 8, 1, 1)
        self.timerLabel = QtWidgets.QLabel(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timerLabel.sizePolicy().hasHeightForWidth())
        self.timerLabel.setSizePolicy(sizePolicy)
        self.timerLabel.setObjectName("timerLabel")
        self.statusBar.addWidget(self.timerLabel, 0, 3, 1, 1)
        self.pause_restartButton = QtWidgets.QToolButton(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_restartButton.sizePolicy().hasHeightForWidth())
        self.pause_restartButton.setSizePolicy(sizePolicy)
        self.pause_restartButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pause_restartButton.setStyleSheet("border: 0px solid black")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/action_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_restartButton.setIcon(icon6)
        self.pause_restartButton.setIconSize(QtCore.QSize(22, 22))
        self.pause_restartButton.setObjectName("pause_restartButton")
        self.statusBar.addWidget(self.pause_restartButton, 0, 5, 1, 1)
        self.stopButton = QtWidgets.QToolButton(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setBaseSize(QtCore.QSize(25, 0))
        self.stopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopButton.setStyleSheet("border: 0px solid black")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/action_finish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon7)
        self.stopButton.setIconSize(QtCore.QSize(22, 22))
        self.stopButton.setObjectName("stopButton")
        self.statusBar.addWidget(self.stopButton, 0, 2, 1, 1)
        self.todayButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.todayButton.setBaseSize(QtCore.QSize(13, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.todayButton.setFont(font)
        self.todayButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.todayButton.setStyleSheet("border: 0px black")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/inbox_notempty.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.todayButton.setIcon(icon8)
        self.todayButton.setIconSize(QtCore.QSize(18, 18))
        self.todayButton.setObjectName("todayButton")
        self.statusBar.addWidget(self.todayButton, 0, 12, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.statusBar.addItem(spacerItem1, 0, 14, 1, 1)
        self.status_message = QtWidgets.QLabel(self.uiCentralWidget)
        self.status_message.setText("")
        self.status_message.setObjectName("status_message")
        self.statusBar.addWidget(self.status_message, 0, 6, 1, 1)
        self.calendarButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.calendarButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calendarButton.setStyleSheet("border: 0px")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/folders_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendarButton.setIcon(icon9)
        self.calendarButton.setIconSize(QtCore.QSize(24, 24))
        self.calendarButton.setObjectName("calendarButton")
        self.statusBar.addWidget(self.calendarButton, 0, 1, 1, 1)
        self.errorButton = QtWidgets.QToolButton(self.uiCentralWidget)
        self.errorButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.errorButton.setStyleSheet("border: 0pt")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.errorButton.setIcon(icon10)
        self.errorButton.setIconSize(QtCore.QSize(20, 20))
        self.errorButton.setObjectName("errorButton")
        self.statusBar.addWidget(self.errorButton, 0, 13, 1, 1)
        self.gridLayout.addLayout(self.statusBar, 3, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.uiCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dayPage = QtWidgets.QWidget()
        self.dayPage.setObjectName("dayPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dayPage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dayTree = QtWidgets.QTreeView(self.dayPage)
        self.dayTree.setMinimumSize(QtCore.QSize(0, 0))
        self.dayTree.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dayTree.setToolTip("")
        self.dayTree.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dayTree.setStyleSheet("border: 0px")
        self.dayTree.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.dayTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dayTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dayTree.setLineWidth(0)
        self.dayTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dayTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dayTree.setAutoScroll(True)
        self.dayTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dayTree.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dayTree.setUniformRowHeights(True)
        self.dayTree.setItemsExpandable(True)
        self.dayTree.setWordWrap(False)
        self.dayTree.setHeaderHidden(True)
        self.dayTree.setObjectName("dayTree")
        self.dayTree.header().setVisible(False)
        self.dayTree.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.dayTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dayPage)
        self.weekPage = QtWidgets.QWidget()
        self.weekPage.setStyleSheet("background: white ")
        self.weekPage.setObjectName("weekPage")
        self.stackedWidget.addWidget(self.weekPage)
        self.monthPage = QtWidgets.QWidget()
        self.monthPage.setStyleSheet("background: white")
        self.monthPage.setObjectName("monthPage")
        self.stackedWidget.addWidget(self.monthPage)
        self.nowPage = QtWidgets.QWidget()
        self.nowPage.setObjectName("nowPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.nowPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nowTree = QtWidgets.QTreeView(self.nowPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nowTree.sizePolicy().hasHeightForWidth())
        self.nowTree.setSizePolicy(sizePolicy)
        self.nowTree.setMinimumSize(QtCore.QSize(0, 0))
        self.nowTree.setAutoFillBackground(False)
        self.nowTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nowTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.nowTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nowTree.setIndentation(20)
        self.nowTree.setUniformRowHeights(True)
        self.nowTree.setHeaderHidden(True)
        self.nowTree.setObjectName("nowTree")
        self.nowTree.header().setVisible(False)
        self.gridLayout_2.addWidget(self.nowTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.nowPage)
        self.nextPage = QtWidgets.QWidget()
        self.nextPage.setObjectName("nextPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.nextPage)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.nextTree = QtWidgets.QTreeView(self.nextPage)
        self.nextTree.setStyleSheet("font-size: 13px")
        self.nextTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nextTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.nextTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.nextTree.setUniformRowHeights(True)
        self.nextTree.setHeaderHidden(True)
        self.nextTree.setObjectName("nextTree")
        self.nextTree.header().setVisible(False)
        self.gridLayout_4.addWidget(self.nextTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.nextPage)
        self.folderPage = QtWidgets.QWidget()
        self.folderPage.setObjectName("folderPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.folderPage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.folderTree = QtWidgets.QTreeView(self.folderPage)
        self.folderTree.setMinimumSize(QtCore.QSize(0, 0))
        self.folderTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.folderTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.folderTree.setLineWidth(0)
        self.folderTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.folderTree.setUniformRowHeights(True)
        self.folderTree.setHeaderHidden(True)
        self.folderTree.setObjectName("folderTree")
        self.gridLayout_5.addWidget(self.folderTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.folderPage)
        self.keywordPage = QtWidgets.QWidget()
        self.keywordPage.setObjectName("keywordPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.keywordPage)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.keywordTree = QtWidgets.QTreeView(self.keywordPage)
        self.keywordTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.keywordTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.keywordTree.setUniformRowHeights(True)
        self.keywordTree.setObjectName("keywordTree")
        self.keywordTree.header().setVisible(False)
        self.gridLayout_10.addWidget(self.keywordTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.keywordPage)
        self.tagPage = QtWidgets.QWidget()
        self.tagPage.setObjectName("tagPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tagPage)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tagTree = QtWidgets.QTreeView(self.tagPage)
        self.tagTree.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tagTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tagTree.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tagTree.setUniformRowHeights(True)
        self.tagTree.setHeaderHidden(True)
        self.tagTree.setObjectName("tagTree")
        self.tagTree.header().setVisible(False)
        self.gridLayout_6.addWidget(self.tagTree, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.tagPage)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        uiMainWindow.setCentralWidget(self.uiCentralWidget)
        self.actionView = QtWidgets.QAction(uiMainWindow)
        self.actionView.setEnabled(False)
        self.actionView.setObjectName("actionView")
        self.actionAdd = QtWidgets.QAction(uiMainWindow)
        self.actionAdd.setEnabled(False)
        self.actionAdd.setObjectName("actionAdd")
        self.actionNew_project = QtWidgets.QAction(uiMainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionEdit_project = QtWidgets.QAction(uiMainWindow)
        self.actionEdit_project.setObjectName("actionEdit_project")
        self.actionNew_project_2 = QtWidgets.QAction(uiMainWindow)
        self.actionNew_project_2.setObjectName("actionNew_project_2")
        self.actionNew_action = QtWidgets.QAction(uiMainWindow)
        self.actionNew_action.setObjectName("actionNew_action")
        self.actionFinish_task = QtWidgets.QAction(uiMainWindow)
        self.actionFinish_task.setObjectName("actionFinish_task")
        self.actionDelete_item = QtWidgets.QAction(uiMainWindow)
        self.actionDelete_item.setObjectName("actionDelete_item")
        self.actionNow = QtWidgets.QAction(uiMainWindow)
        self.actionNow.setObjectName("actionNow")
        self.actionNext = QtWidgets.QAction(uiMainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionDay = QtWidgets.QAction(uiMainWindow)
        self.actionDay.setObjectName("actionDay")
        self.actionWeek = QtWidgets.QAction(uiMainWindow)
        self.actionWeek.setObjectName("actionWeek")
        self.actionMonth = QtWidgets.QAction(uiMainWindow)
        self.actionMonth.setObjectName("actionMonth")
        self.actionProject = QtWidgets.QAction(uiMainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionNotes = QtWidgets.QAction(uiMainWindow)
        self.actionNotes.setObjectName("actionNotes")
        self.actionActions = QtWidgets.QAction(uiMainWindow)
        self.actionActions.setObjectName("actionActions")
        self.action_5 = QtWidgets.QAction(uiMainWindow)
        self.action_5.setObjectName("action_5")
        self.actionCustom = QtWidgets.QAction(uiMainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionSelection_details = QtWidgets.QAction(uiMainWindow)
        self.actionSelection_details.setObjectName("actionSelection_details")
        self.actionSelection_history_2 = QtWidgets.QAction(uiMainWindow)
        self.actionSelection_history_2.setObjectName("actionSelection_history_2")
        self.actionNew_action_2 = QtWidgets.QAction(uiMainWindow)
        self.actionNew_action_2.setObjectName("actionNew_action_2")
        self.actionPause_running_action = QtWidgets.QAction(uiMainWindow)
        self.actionPause_running_action.setEnabled(False)
        self.actionPause_running_action.setObjectName("actionPause_running_action")
        self.actionRestart = QtWidgets.QAction(uiMainWindow)
        self.actionRestart.setEnabled(False)
        self.actionRestart.setObjectName("actionRestart")
        self.actionRecord = QtWidgets.QAction(uiMainWindow)
        self.actionRecord.setEnabled(False)
        self.actionRecord.setObjectName("actionRecord")
        self.actionEdit = QtWidgets.QAction(uiMainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionFinish = QtWidgets.QAction(uiMainWindow)
        self.actionFinish.setObjectName("actionFinish")
        self.actionDelete = QtWidgets.QAction(uiMainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionMove = QtWidgets.QAction(uiMainWindow)
        self.actionMove.setObjectName("actionMove")
        self.actionAll_day_event = QtWidgets.QAction(uiMainWindow)
        self.actionAll_day_event.setObjectName("actionAll_day_event")
        self.actionEvent = QtWidgets.QAction(uiMainWindow)
        self.actionEvent.setObjectName("actionEvent")
        self.actionTask = QtWidgets.QAction(uiMainWindow)
        self.actionTask.setObjectName("actionTask")
        self.actionTask_group = QtWidgets.QAction(uiMainWindow)
        self.actionTask_group.setObjectName("actionTask_group")
        self.actionDelegated_task = QtWidgets.QAction(uiMainWindow)
        self.actionDelegated_task.setObjectName("actionDelegated_task")
        self.actionIn_basket = QtWidgets.QAction(uiMainWindow)
        self.actionIn_basket.setObjectName("actionIn_basket")
        self.actionSomeday_maybe = QtWidgets.QAction(uiMainWindow)
        self.actionSomeday_maybe.setObjectName("actionSomeday_maybe")
        self.actionFind = QtWidgets.QAction(uiMainWindow)
        self.actionFind.setObjectName("actionFind")

        self.retranslateUi(uiMainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(uiMainWindow)

    def retranslateUi(self, uiMainWindow):
        _translate = QtCore.QCoreApplication.translate
        uiMainWindow.setWindowTitle(_translate("uiMainWindow", "etm"))
        self.uiView.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-L</em> to select the view."))
        self.newItemButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-N</em>  to create a new event, note or task."))
        self.newItemButton.setText(_translate("uiMainWindow", "..."))
        self.newActionButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-T</em> to start a timer for a new action."))
        self.newActionButton.setText(_translate("uiMainWindow", "..."))
        self.reportButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-R</em> to create a report."))
        self.reportButton.setText(_translate("uiMainWindow", "report"))
        self.uiFilter.setToolTip(_translate("uiMainWindow", "Click here or press Ctrl-F to enter a pattern to limit\n"
"the display to items from matching branches."))
        self.uiFilter.setPlaceholderText(_translate("uiMainWindow", "filter"))
        self.mainHelpButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>F1</em> to view help information."))
        self.mainHelpButton.setText(_translate("uiMainWindow", "Settings"))
        self.alertsButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-A</em> to see the remaining alerts for today."))
        self.alertsButton.setText(_translate("uiMainWindow", "..."))
        self.currentTime.setText(_translate("uiMainWindow", "current time"))
        self.timerLabel.setText(_translate("uiMainWindow", "0:00"))
        self.pause_restartButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-T</em> to pause the timer."))
        self.pause_restartButton.setText(_translate("uiMainWindow", "..."))
        self.stopButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Shift Ctrl-T</em> to stop the timer and record the action."))
        self.stopButton.setText(_translate("uiMainWindow", "..."))
        self.todayButton.setToolTip(_translate("uiMainWindow", "Click here or press the <em>semi-colon</em> key to view past due items."))
        self.todayButton.setText(_translate("uiMainWindow", "..."))
        self.calendarButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-C</em> to choose the active calendars."))
        self.calendarButton.setText(_translate("uiMainWindow", "..."))
        self.errorButton.setToolTip(_translate("uiMainWindow", "Click here or press <em>Ctrl-E</em> to see data error messages."))
        self.errorButton.setText(_translate("uiMainWindow", "..."))
        self.actionView.setText(_translate("uiMainWindow", "View"))
        self.actionAdd.setText(_translate("uiMainWindow", "Add"))
        self.actionNew_project.setText(_translate("uiMainWindow", "New project"))
        self.actionEdit_project.setText(_translate("uiMainWindow", "Edit project"))
        self.actionNew_project_2.setText(_translate("uiMainWindow", "New project"))
        self.actionNew_action.setText(_translate("uiMainWindow", "New action"))
        self.actionFinish_task.setText(_translate("uiMainWindow", "Finish task"))
        self.actionDelete_item.setText(_translate("uiMainWindow", "Delete item"))
        self.actionNow.setText(_translate("uiMainWindow", "Now"))
        self.actionNext.setText(_translate("uiMainWindow", "Next"))
        self.actionDay.setText(_translate("uiMainWindow", "Day"))
        self.actionWeek.setText(_translate("uiMainWindow", "Week"))
        self.actionMonth.setText(_translate("uiMainWindow", "Month"))
        self.actionProject.setText(_translate("uiMainWindow", "Project"))
        self.actionNotes.setText(_translate("uiMainWindow", "Notes"))
        self.actionActions.setText(_translate("uiMainWindow", "Actions"))
        self.action_5.setText(_translate("uiMainWindow", "Selection history"))
        self.actionCustom.setText(_translate("uiMainWindow", "Custom"))
        self.actionSelection_details.setText(_translate("uiMainWindow", "Selection details"))
        self.actionSelection_history_2.setText(_translate("uiMainWindow", "Selection history"))
        self.actionNew_action_2.setText(_translate("uiMainWindow", "New"))
        self.actionPause_running_action.setText(_translate("uiMainWindow", "Pause"))
        self.actionRestart.setText(_translate("uiMainWindow", "Restart"))
        self.actionRecord.setText(_translate("uiMainWindow", "Record"))
        self.actionEdit.setText(_translate("uiMainWindow", "Edit"))
        self.actionFinish.setText(_translate("uiMainWindow", "Finish"))
        self.actionDelete.setText(_translate("uiMainWindow", "Delete"))
        self.actionMove.setText(_translate("uiMainWindow", "Move"))
        self.actionAll_day_event.setText(_translate("uiMainWindow", "all day event"))
        self.actionAll_day_event.setShortcut(_translate("uiMainWindow", "Ctrl+L"))
        self.actionEvent.setText(_translate("uiMainWindow", "event"))
        self.actionEvent.setShortcut(_translate("uiMainWindow", "Ctrl+E"))
        self.actionTask.setText(_translate("uiMainWindow", "task"))
        self.actionTask.setShortcut(_translate("uiMainWindow", "Ctrl+T"))
        self.actionTask_group.setText(_translate("uiMainWindow", "task group"))
        self.actionTask_group.setShortcut(_translate("uiMainWindow", "Ctrl+G"))
        self.actionDelegated_task.setText(_translate("uiMainWindow", "delegated task"))
        self.actionDelegated_task.setShortcut(_translate("uiMainWindow", "Ctrl+D"))
        self.actionIn_basket.setText(_translate("uiMainWindow", "in basket"))
        self.actionIn_basket.setShortcut(_translate("uiMainWindow", "Ctrl+I"))
        self.actionSomeday_maybe.setText(_translate("uiMainWindow", "someday maybe"))
        self.actionSomeday_maybe.setShortcut(_translate("uiMainWindow", "Ctrl+S"))
        self.actionFind.setText(_translate("uiMainWindow", "find"))

