
# parsetabs/abstract_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x1e\x8c\x10\xd6\xed\x93/\xdd\x0fW\xc2\x89:\xc4\xc3\xfe'
    
_lr_action_items = {'FLOAT':([7,],[9,]),'ABSTRACT':([0,],[3,]),'PATH':([7,],[13,]),'DEFAULT_FIELD':([7,],[14,]),'EMAIL':([7,],[19,]),'BIN':([7,],[16,]),'WORD':([7,],[17,]),'NBSTR':([7,],[18,]),'OCT':([7,],[15,]),'$end':([1,2,3,4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,],[-6,0,-9,-12,-20,-23,-26,-24,-15,-22,-16,-27,-21,-18,-1,-10,-11,-2,-19,-14,-8,-4,-28,-5,-3,-25,-7,-17,-13,-29,]),'IPV4ADDR':([7,],[23,]),'US_PHONE':([7,],[21,]),'URL':([7,],[22,]),'ABSTRACT_OPT':([3,6,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,],[5,5,-26,-24,-15,-22,-16,-27,-21,-18,-1,-10,-11,-2,-19,-14,-8,-4,-28,-5,-3,-25,-7,-17,-13,-29,]),'HEX':([7,],[12,]),'LITERAL':([7,],[24,]),'INTERNAL_FIELD':([7,],[25,]),'IPV6ADDR':([7,],[26,]),'EQ':([5,],[7,]),'ID':([7,],[27,]),'INT':([7,],[28,]),'HOSTNAME':([7,],[29,]),'WILDCARD':([7,],[31,]),'DEFAULT_DATETIME_FIELD':([7,],[32,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[2,]),'wc_stringlist':([3,6,],[4,8,]),'int':([7,],[10,]),'abstractcmd':([0,],[1,]),'value':([7,],[30,]),'wc_string':([3,6,],[6,6,]),'field':([7,],[20,]),'num':([7,],[11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('field -> WORD','field',1,'p_field_word','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',5),
  ('value -> field','value',1,'p_value_times','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',7),
  ('field -> ID','field',1,'p_field_id','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',9),
  ('field -> LITERAL','field',1,'p_field_literal','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',13),
  ('value -> IPV6ADDR','value',1,'p_value_ipv6addr','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',13),
  ('cmdexpr -> abstractcmd','cmdexpr',1,'p_cmdexpr_abstract','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',17),
  ('field -> HOSTNAME','field',1,'p_field_hostname','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',17),
  ('value -> IPV4ADDR','value',1,'p_value_ipv4addr','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',17),
  ('abstractcmd -> ABSTRACT','abstractcmd',1,'p_cmdexpr_abstract_single','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',21),
  ('field -> NBSTR','field',1,'p_field_nbstr','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',21),
  ('value -> EMAIL','value',1,'p_value_email','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',21),
  ('abstractcmd -> ABSTRACT wc_stringlist','abstractcmd',2,'p_addtotalscmd_abstract','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',25),
  ('field -> WILDCARD','field',1,'p_field_wildcard','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',25),
  ('value -> URL','value',1,'p_value_url','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',25),
  ('field -> num','field',1,'p_field_num','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',29),
  ('value -> PATH','value',1,'p_value_path','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',29),
  ('wc_string -> ABSTRACT_OPT EQ value','wc_string',3,'p_abstract_opt','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',30),
  ('num -> BIN','num',1,'p_num_bin','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',33),
  ('value -> US_PHONE','value',1,'p_value_us_phone','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',33),
  ('wc_stringlist -> wc_string','wc_stringlist',1,'p_abstract_opt_list','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',37),
  ('num -> OCT','num',1,'p_num_oct','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',37),
  ('num -> HEX','num',1,'p_num_hex','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',41),
  ('wc_stringlist -> wc_string wc_stringlist','wc_stringlist',2,'p_abstract_optlist','/Users/salspaugh/splparser/splparser/rules/abstractrules.py',42),
  ('num -> int','num',1,'p_num_int','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',45),
  ('int -> INT','int',1,'p_posint','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',49),
  ('num -> FLOAT','num',1,'p_num_float','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',53),
  ('field -> DEFAULT_FIELD','field',1,'p_field_default_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',57),
  ('field -> INTERNAL_FIELD','field',1,'p_field_internal_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',61),
  ('field -> DEFAULT_DATETIME_FIELD','field',1,'p_field_default_datetime_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',65),
]
