
# parsetabs/localop_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'XvA\x03\xf7#*4\x0b{-\xbd\xd9\x9f\x9c\xc1'
    
_lr_action_items = {'LOCALOP':([0,],[2,]),'$end':([1,2,3,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[1,]),'localopcmd':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('cmdexpr -> localopcmd','cmdexpr',1,'p_cmdexpr_localop','/Users/salspaugh/splparser/splparser/rules/localoprules.py',11),
  ('localopcmd -> LOCALOP','localopcmd',1,'p_cmdexpr_localop_debug','/Users/salspaugh/splparser/splparser/rules/localoprules.py',15),
]
