
# parsetabs/relevancy_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x9b\x1a@\x91ig\x9c\x0f\xb3FZ\x07\x8e\xb9\xb3\xb7'
    
_lr_action_items = {'RELEVANCY':([0,],[3,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[1,]),'relevancycmd':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('cmdexpr -> relevancycmd','cmdexpr',1,'p_cmdexpr_relevancy','/Users/salspaugh/splparser/splparser/rules/relevancyrules.py',11),
  ('relevancycmd -> RELEVANCY','relevancycmd',1,'p_cmdexpr_relevancy_debug','/Users/salspaugh/splparser/splparser/rules/relevancyrules.py',15),
]
