
# parsetabs/uniq_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe0\xc4\xc99\x9f\xf7\x1f\xf0\x11Iu\x16\xab|8Q'
    
_lr_action_items = {'UNIQ':([0,],[2,]),'$end':([1,2,3,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[1,]),'uniqcmd':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('cmdexpr -> uniqcmd','cmdexpr',1,'p_cmdexpr_uniq','/Users/salspaugh/splparser/splparser/rules/uniqrules.py',11),
  ('uniqcmd -> UNIQ','uniqcmd',1,'p_cmdexpr_uniq_debug','/Users/salspaugh/splparser/splparser/rules/uniqrules.py',15),
]
