
# parsetabs/xmlkv_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc3\xc2\x85\x0e\xc3Q\x14\xfdO\xf6F\xb2\x04E\xb2\xdb'
    
_lr_action_items = {'FLOAT':([8,],[9,]),'XMLKV':([0,],[3,]),'PATH':([8,],[12,]),'DEFAULT_FIELD':([8,],[13,]),'EMAIL':([8,],[18,]),'XMLKV_OPT':([3,5,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,],[6,6,-26,-24,-15,-16,-27,-21,-18,-1,-10,-11,-2,-19,-14,-22,-8,-4,-28,-5,-3,-25,-7,-17,-13,-29,]),'BIN':([8,],[15,]),'WORD':([8,],[16,]),'NBSTR':([8,],[17,]),'OCT':([8,],[14,]),'$end':([1,2,3,4,5,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,],[-6,0,-9,-12,-20,-23,-26,-24,-15,-16,-27,-21,-18,-1,-10,-11,-2,-19,-14,-22,-8,-4,-28,-5,-3,-25,-7,-17,-13,-29,]),'US_PHONE':([8,],[20,]),'URL':([8,],[21,]),'HEX':([8,],[22,]),'IPV4ADDR':([8,],[23,]),'LITERAL':([8,],[24,]),'INTERNAL_FIELD':([8,],[25,]),'IPV6ADDR':([8,],[26,]),'EQ':([6,],[8,]),'ID':([8,],[27,]),'INT':([8,],[28,]),'HOSTNAME':([8,],[29,]),'WILDCARD':([8,],[31,]),'DEFAULT_DATETIME_FIELD':([8,],[32,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmdexpr':([0,],[2,]),'wc_stringlist':([3,5,],[4,7,]),'int':([8,],[10,]),'value':([8,],[30,]),'wc_string':([3,5,],[5,5,]),'xmlkvcmd':([0,],[1,]),'field':([8,],[19,]),'num':([8,],[11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmdexpr","S'",1,None,None,None),
  ('field -> WORD','field',1,'p_field_word','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',5),
  ('value -> field','value',1,'p_value_times','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',7),
  ('field -> ID','field',1,'p_field_id','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',9),
  ('field -> LITERAL','field',1,'p_field_literal','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',13),
  ('value -> IPV6ADDR','value',1,'p_value_ipv6addr','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',13),
  ('cmdexpr -> xmlkvcmd','cmdexpr',1,'p_cmdexpr_xmlkv','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',16),
  ('field -> HOSTNAME','field',1,'p_field_hostname','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',17),
  ('value -> IPV4ADDR','value',1,'p_value_ipv4addr','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',17),
  ('xmlkvcmd -> XMLKV','xmlkvcmd',1,'p_cmdexpr_xmlkv_single','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',20),
  ('field -> NBSTR','field',1,'p_field_nbstr','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',21),
  ('value -> EMAIL','value',1,'p_value_email','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',21),
  ('xmlkvcmd -> XMLKV wc_stringlist','xmlkvcmd',2,'p_cmdexpr_xmlkv_field','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',24),
  ('field -> WILDCARD','field',1,'p_field_wildcard','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',25),
  ('value -> URL','value',1,'p_value_url','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',25),
  ('field -> num','field',1,'p_field_num','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',29),
  ('value -> PATH','value',1,'p_value_path','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',29),
  ('wc_string -> XMLKV_OPT EQ value','wc_string',3,'p_xmlkv_opt','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',29),
  ('num -> BIN','num',1,'p_num_bin','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',33),
  ('value -> US_PHONE','value',1,'p_value_us_phone','/Users/salspaugh/splparser/splparser/rules/common/valuerules.py',33),
  ('wc_stringlist -> wc_string','wc_stringlist',1,'p_xmlkv_opt_list','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',36),
  ('num -> OCT','num',1,'p_num_oct','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',37),
  ('num -> HEX','num',1,'p_num_hex','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',41),
  ('wc_stringlist -> wc_string wc_stringlist','wc_stringlist',2,'p_xmlkv_optlist','/Users/salspaugh/splparser/splparser/rules/xmlkvrules.py',41),
  ('num -> int','num',1,'p_num_int','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',45),
  ('int -> INT','int',1,'p_posint','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',49),
  ('num -> FLOAT','num',1,'p_num_float','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',53),
  ('field -> DEFAULT_FIELD','field',1,'p_field_default_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',57),
  ('field -> INTERNAL_FIELD','field',1,'p_field_internal_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',61),
  ('field -> DEFAULT_DATETIME_FIELD','field',1,'p_field_default_datetime_field','/Users/salspaugh/splparser/splparser/rules/common/fieldrules.py',65),
]
