#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `hr_expense` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-hr-expense",
    version = "7.0.355",
    description = "Expense Management",
    long_description = 
"""

Manage expenses by Employees
============================

This application allows you to manage your employees' daily expenses. It gives you access to your employees’ fee notes and give you the right to complete and validate or refuse the notes. After validation it creates an invoice for the employee.
Employee can encode their own expenses and the validation flow puts it automatically in the accounting after validation by managers.


The whole flow is implemented as:
---------------------------------
* Draft expense
* Confirmation of the sheet by the employee
* Validation by his manager
* Validation by the accountant and receipt creation

This module also uses analytic accounting and is compatible with the invoice on timesheet module so that you are able to automatically re-invoice your customers' expenses if your work by project.
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.hr_expense': ".",
    },
    packages = ["openerp.addons.hr_expense","openerp.addons.hr_expense.report"],
    package_data = {
        'openerp.addons.hr_expense': ["i18n/*.po*","hr_expense_report.xml","board_hr_expense_view.xml","hr_expense_workflow.xml","hr.expense.expense.csv","hr_expense_demo.xml","hr_expense_view.xml","hr_expense_data.xml","hr_expense_installer_view.xml","hr_expense_sequence.xml","images/hr_expenses_analysis.jpeg","images/hr_expenses.jpeg","static/src/img/icon.png","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/th.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/expense_process.yml","test/expense_demo.yml","security/ir.model.access.csv","security/ir_rule.xml","report/expense.rml","report/expense.sxw","report/hr_expense_report_view.xml","process/hr_expense_process.xml","security/ir.model.access.csv","hr_expense_data.xml","hr_expense_sequence.xml","hr_expense_workflow.xml","hr_expense_view.xml","hr_expense_report.xml","process/hr_expense_process.xml","security/ir_rule.xml","report/hr_expense_report_view.xml","board_hr_expense_view.xml","hr_expense_installer_view.xml","hr_expense_demo.xml"],
    },
    install_requires = ["openerp-hr","openerp-account-voucher","openerp-account-accountant"],
    tests_require = ["unittest2"],
)
