__version__ = "0.2.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1995e5326ed5ef965345466a1757e153f37fea86'
__git_head_subject__ = 'STORAGEMODEL-252 fixing KeyError'
__git_head_message__ = ''
__git_dirty_diff__ = ''