language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.5
    - python: 3.2
      env: DJANGO=1.3.7
    - python: 3.3
      env: DJANGO=1.4.5
    - python: 3.3
      env: DJANGO=1.3.7
