
CONFIG_YAML = "CONFIG_YAML"
JOB_ROOT_DIR = "JOB_ROOT_DIR"
JOB_STATE = "JOB_STATE"
SUSPENDED_FILE = "SUSPENDED_FILE"
SUSPENDED_TASKS = "SUSPENDED_TASKS"
SECRET_KEY = "SECRET_KEY"

LOG_COUNT = "LOG_COUNT"
LOG_MAX_SIZE = "LOG_MAX_SIZE"
LOG_DIR = "LOG_DIR"

SPEEDRACK_DIR = "SPEEDRACK_DIR"

APP_NAME = "APP_NAME"

FLASK_DEBUG_TOOLBAR = "FLASK_DEBUG_TOOLBAR"
SECRET_KEY = "SECRET_KEY"

EMAIL_DISABLED = "EMAIL_DISABLED"
EMAIL_TO_GLOBAL = "EMAIL_TO_GLOBAL"
EMAIL_FROM_ADDRESS = "EMAIL_FROM_ADDRESS"
EMAIL_SMTP = "EMAIL_SMTP"

URL_ROOT = "URL_ROOT"
PORT = "PORT"

FAIL_BY_STDERR = "FAIL_BY_STDERR"
FAIL_BY_RETCODE = "FAIL_BY_RETCODE"

SCRIPT_NAME = "SCRIPT_NAME"
EMAIL_URL_PREFIX = "EMAIL_URL_PREFIX"

# params
import task_params

# task status
FAILED = "failed"
SUCCESS = "success"
