target_folder: "target"
default_folder: "default"
original_move_folder: "temp/originals"
evernote_developer_token: "S=s1:U=889c2:E=1493ed0d350:C=141e71fa753:P=1cd:A=en-devtoken:V=2:H=3b99efdea7ff9c8db33f32f1dd0bbc35"

mail_smtp_server: "smtp.gmail.com:587"
mail_smtp_login: "virantha@gmail.com"
mail_smtp_password: "cctahvuntxbuwmox"
mail_from_addr: "virantha#gmail.com"
mail_to_list: 
    - "virantha@gmail.com"

tesseract:
    binary: "tesseract"

# Filing Folder list
folders:
    acx:
        - Achronix
    daycare:
        - columbia academy
    health:
        - bluecross
        - blue cross
        - aetna
        - explanation of benefit
    home:
        - mortgage
        - property tax
        - encompass
        - baltimore city
    auto:
        - parking citation
        - dmv
        - mva
        - farmers
        - geico
    finances:
        - college savings
        - "529"
        - 401K 
        - chase card
        - expense report
        - american express
        - tax information
        - irs
        - tax statement
        - income tax
        - internal revenue service
        - earnings statement
        - discover more card
    travel:
        - boarding pass
        - airlines
        - expedia
        - orbitz
        - airways
    receipts:
        - receipt
     


