#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `crm_profiling` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-crm-profiling",
    version = "7.0.355",
    description = "Customer Profiling",
    long_description = 
"""

This module allows users to perform segmentation within partners.
=================================================================

It uses the profiles criteria from the earlier segmentation module and improve it. 
Thanks to the new concept of questionnaire. You can now regroup questions into a 
questionnaire and directly use it on a partner.

It also has been merged with the earlier CRM & SRM segmentation tool because they 
were overlapping.

    **Note:** this module is not compatible with the module segmentation, since it's the same which has been renamed.
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.crm_profiling': ".",
    },
    packages = ["openerp.addons.crm_profiling","openerp.addons.crm_profiling.wizard"],
    package_data = {
        'openerp.addons.crm_profiling': ["i18n/*.po*","crm_profiling_demo.xml","crm_profiling_view.xml","images/profiling_questions.jpeg","images/profiling_questionnaires.jpeg","i18n/sk.po","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/gu.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/es_PY.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/gl.po","i18n/lv.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/process/profiling.yml","security/ir.model.access.csv","wizard/open_questionnaire_view.xml","security/ir.model.access.csv","wizard/open_questionnaire_view.xml","crm_profiling_view.xml","crm_profiling_demo.xml"],
    },
    install_requires = ["openerp-core","openerp-crm"],
    tests_require = ["unittest2"],
)
