
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.3'
version_full = '2696b133b7ec19f34dcfb206b34689cf90d459e4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

