
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.8'
version_full = '496036f15cf257d16b6594770812da64a249280c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

