language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r dev-requirements.txt --use-mirrors"
  - "case \"`python -V 2>&1`\" in *2.6*) pip install unittest2 --use-mirrors; esac"
  - "python setup.py build"
script: nosetests
