
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = 'e0aff4d097060bad2884a780971cf249652e8f41'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

