language: python

install:
  - "wget -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list"
  - "sudo apt-get update || true"
  - "sudo apt-get install $(apt-cache depends mopidy-soundcloud | awk '$2 !~ /mopidy-soundcloud|python:any/ {print $2}')"
  - "pip install coveralls flake8 mopidy==dev"

before_script:
  - "rm $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt"

script:
  - "flake8 mopidy_soundcloud tests"
  - "nosetests --with-coverage --cover-package=mopidy_soundcloud"

after_success:
  - "coveralls"

branches:
   except:
     - debian

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true

deploy:
  provider: pypi
  user: janez.troha
  password:
    secure: JCJ8yvOeytrzODupwDLfUIVV8fAJVq7Bm09B0vo4YhWEn90XUhBk2A3s/+nSaEZ9rAgbAerddsyCGFV6K9svzP5h1+6PLbU+s775JfjU/KqyJxaJmRdrVp33Cvadukuq8mV8d+z+tTI6acK/Wq9XpmYLRFVH4TX829TN1fzox8U=
  on:
    tags: true
    repo: mopidy/mopidy-soundcloud