__version__ = "0.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '125bf7816abf46199927b659689188a621dd6c9e'
__git_head_subject__ = 'Finished release v0.2.'
__git_head_message__ = '* release/v0.2:\n  changing PIL/Pillow imports\n  buildout.cfg: adding Pillow to requirements\n  buildout.cfg: remove PIL from requirements'
__git_dirty_diff__ = ''