language: python
python:
  - "3.2"
  - "2.7"
  - "2.6"
install:
  - python setup.py develop
  - pip install --use-mirrors nose coverage
script:
  nosetests --with-coverage --cover-package=perfmetrics --cover-branches
