__version__ = "0.2.9"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5e30de1a0a9a595155268329c4d16ee9ed9f4ff7'
__git_head_subject__ = 'Finished release v0.2.9.'
__git_head_message__ = '* release/v0.2.9:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  update dependencies'
__git_dirty_diff__ = ''