__version__ = "0.0.9"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.0.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '4ee4ac2a516a9f5e468e41ec8e01878c1696434d'
__git_head_subject__ = 'Finished release v0.0.9.'
__git_head_message__ = ''
__git_dirty_diff__ = ''