__version__ = "0.1.7"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd376f5f75df2fd592740cc5b467f281a5fbd4700'
__git_head_subject__ = 'Finished release v0.1.7.'
__git_head_message__ = '* release/v0.1.7:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements\n  buildout.cfg: remove infi.recipe.console-scripts from requirements\n  update dependencies'
__git_dirty_diff__ = ''