__version__ = "0.2.6"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.6)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '6a0c2a2bf8c51d815585718dadef06f1d87c291b'
__git_head_subject__ = 'Finished release v0.2.6.'
__git_head_message__ = '* release/v0.2.6:\n  STORAGEMODEL-256 fixing typo\n  STORAGEMODEL-258 adding support for the new inquiry pages in InfiniBox 1.5\n  flake8 fixes\n  TRIVIAL updated checkout instructions in README.md\n  buildout.cfg: changed isolated python version to v2.7.5.5\n  TRIVIAL gitignore\n  TRIVIAL gitignore\n  TRIVIAL gitignore'
__git_dirty_diff__ = ''