__version__ = "0.1.2"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@infinigit.infinidat.com:/host/monotonic-time.git'
__git_head_hash__ = '61b477771642ae0027789ed4c60d9efca415266d'
__git_head_subject__ = 'Finished release v0.1.2.'
__git_head_message__ = ''
__git_dirty_diff__ = ''