language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3 QA=true
matrix:
  global:
    - secure: "PiqlxDfjGi0j9uUl0p/fBzt9YzvzKwMCgae+5xZPdRocNd68gRv1O7XQslDo\nE/nzXhrwAz1G+9JcTbfjAgnNhc2V1pCpLf2ZQRQaYsoIlVb0CPHQXbblRAL/\nz2pYgpcZaClkbGrsjmkg0bTE5Y43cwfPwuQVhAJj7dWaMF58Haw="
  exclude:
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3 QA=true
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  - sudo apt-get install -qq libxml2-dev libxslt-dev
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
install:
  - python bootstrap.py -v 1.6.3 -c test-$PLONE.x.cfg
  - bin/buildout -t 5 -Nqc test-$PLONE.x.cfg
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bin/test
after_success: test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
