__version__ = "0.4.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5356bddc9a892caaf6e8e0678513389c2087864f'
__git_head_subject__ = 'Finished release v0.4.2.'
__git_head_message__ = '* release/v0.4.2:\n  TRIVIAL text for post-install/pre-uninstall custom actions\n  TRIVIAL fix spelling'
__git_dirty_diff__ = ''