#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `portal_project_long_term` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-portal-project-long-term",
    version = "7.0.355",
    description = "Portal Project Long Term",
    long_description = 
"""

This module adds necessary security rules and access rights for project long term and portal.
=============================================================================================
    
""",
    url = "",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.portal_project_long_term': ".",
    },
    packages = ["openerp.addons.portal_project_long_term"],
    package_data = {
        'openerp.addons.portal_project_long_term': ["i18n/*.po*","security/ir.model.access.csv","security/portal_security.xml","security/portal_security.xml","security/ir.model.access.csv"],
    },
    install_requires = ["openerp-project-long-term","openerp-portal"],
    tests_require = ["unittest2"],
)
