language: python
python:
  - "2.7"
notifications:
  email:
    recipients:
    - maurits@vanrees.org
    on_success: change
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg
script: bin/test
