# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.afni.preprocess import Fim
def test_Fim_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(name_source='in_file',
    argstr='-bucket %s',
    name_template='%s_fim',
    ),
    args=dict(argstr='%s',
    ),
    outputtype=dict(),
    fim_thr=dict(position=3,
    argstr='-fim_thr %f',
    ),
    ideal_file=dict(position=2,
    argstr='-ideal_file %s',
    mandatory=True,
    ),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(copyfile=False,
    mandatory=True,
    position=1,
    argstr=' -input %s',
    ),
    out=dict(position=4,
    argstr='-out %s',
    ),
    )
    inputs = Fim.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_Fim_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = Fim.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
