# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.afni.preprocess import TCat
def test_TCat_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(name_source='in_file',
    argstr='-prefix %s',
    name_template='%s_tcat',
    ),
    args=dict(argstr='%s',
    ),
    outputtype=dict(),
    in_files=dict(copyfile=False,
    mandatory=True,
    argstr=' %s',
    position=-1,
    ),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    rlt=dict(position=1,
    argstr='-rlt%s',
    ),
    )
    inputs = TCat.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_TCat_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = TCat.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
