# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from nipype.testing import assert_equal
from nipype.interfaces.afni.preprocess import TShift
def test_TShift_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    tpattern=dict(argstr='-tpattern %s',
    ),
    out_file=dict(name_source='in_file',
    argstr='-prefix %s',
    name_template='%s_tshift',
    ),
    tr=dict(argstr='-TR %s',
    ),
    args=dict(argstr='%s',
    ),
    interp=dict(argstr='-%s',
    ),
    outputtype=dict(),
    tzero=dict(argstr='-tzero %s',
    xor=['tslice'],
    ),
    ignore=dict(argstr='-ignore %s',
    ),
    rltplus=dict(argstr='-rlt+',
    ),
    terminal_output=dict(nohash=True,
    mandatory=True,
    ),
    tslice=dict(argstr='-slice %s',
    xor=['tzero'],
    ),
    in_file=dict(copyfile=False,
    mandatory=True,
    position=-1,
    argstr='%s',
    ),
    rlt=dict(argstr='-rlt',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    )
    inputs = TShift.input_spec()

    for key, metadata in input_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(inputs.traits()[key], metakey), value
def test_TShift_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = TShift.output_spec()

    for key, metadata in output_map.items():
        for metakey, value in metadata.items():
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
