language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python2.6-tk python2.6-gdbm
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis-$PLONE_VERSION.x.cfg
  - bin/buildout -N -t 5 -c travis-$PLONE_VERSION.x.cfg
branches:
  only:
    - master
script: bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
  hipchat:
    secure: "haQNP6AVCh7QkqAqjeB5yrscRyTiGLzgeXUKCGTgA+oH7fHs/UOB2PFuMRdG55qmg6qkFHId9PintevaSThkNmRtmbrwfRIsGqHPyKgcIAybwfPrk3CEFKU4SWP4oTOR9D/zqlWAz/9sEcoMezKDJUyqywsTkfbbO70eztqP/io="
