__version__ = "0.4.5"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.4.5)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '50eb5fc1cecc6a8ff03f046ccc0b45ef10565f53'
__git_head_subject__ = 'bumping expected dependencies in CompilerTestCase.test_get_packages_to_install'
__git_head_message__ = ''
__git_dirty_diff__ = ''