
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.3'
version_full = '880072d2125e2492d4479308ae8b769a4db2541d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

