
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = 'b81d10a0295c4d30e7e4195b9f290b8b28a16388'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

