#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `account_check_writing` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-account-check-writing",
    version = "7.0.355",
    description = "Check Writing",
    long_description = 
"""

Module for the Check Writing and Check Printing.
================================================
    
""",
    url = "http://www.openerp.com",
    author = "OpenERP SA, NovaPoint Group",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.account_check_writing': ".",
    },
    packages = ["openerp.addons.account_check_writing","openerp.addons.account_check_writing.report","openerp.addons.account_check_writing.wizard"],
    package_data = {
        'openerp.addons.account_check_writing': ["i18n/*.po*","account_voucher_view.xml","account_demo.xml","account_check_writing_data.xml","account_check_writing_report.xml","account_view.xml","i18n/hr.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/en_GB.po","i18n/cs.po","i18n/fi.po","i18n/pt_BR.po","i18n/gu.po","i18n/ja.po","i18n/ro.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/lt.po","i18n/hu.po","i18n/mk.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","report/check_print_middle.sxw","report/check_print.sxw","report/check_print_bottom.rml","report/check_print_top.rml","report/check_print_middle.rml","report/check_print_top.sxw","report/check_print_bottom.sxw","wizard/account_check_batch_printing_view.xml","wizard/account_check_batch_printing_view.xml","account_check_writing_report.xml","account_view.xml","account_voucher_view.xml","account_check_writing_data.xml","account_demo.xml"],
    },
    install_requires = ["openerp-account-voucher"],
    tests_require = ["unittest2"],
)
