# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/geoff/work/baserip/baserip/ui/br_mainwindow.ui'
#
# Created: Sun Feb 16 16:10:07 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BR_MainWindow(object):
    def setupUi(self, BR_MainWindow):
        BR_MainWindow.setObjectName(_fromUtf8("BR_MainWindow"))
        BR_MainWindow.resize(455, 641)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BR_MainWindow.sizePolicy().hasHeightForWidth())
        BR_MainWindow.setSizePolicy(sizePolicy)
        BR_MainWindow.setMinimumSize(QtCore.QSize(455, 620))
        BR_MainWindow.setMaximumSize(QtCore.QSize(455, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/baserip.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BR_MainWindow.setWindowIcon(icon)
        BR_MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(BR_MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 451, 601))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSource = QtGui.QWidget()
        self.tabSource.setObjectName(_fromUtf8("tabSource"))
        self.layoutWidget1 = QtGui.QWidget(self.tabSource)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 11, 441, 481))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.DVDTree = QtGui.QTreeView(self.layoutWidget1)
        self.DVDTree.setObjectName(_fromUtf8("DVDTree"))
        self.verticalLayout.addWidget(self.DVDTree)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkALang = QtGui.QCheckBox(self.layoutWidget1)
        self.chkALang.setChecked(True)
        self.chkALang.setObjectName(_fromUtf8("chkALang"))
        self.horizontalLayout_2.addWidget(self.chkALang)
        self.cboALang = QtGui.QComboBox(self.layoutWidget1)
        self.cboALang.setObjectName(_fromUtf8("cboALang"))
        self.horizontalLayout_2.addWidget(self.cboALang)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkSLang = QtGui.QCheckBox(self.layoutWidget1)
        self.chkSLang.setEnabled(True)
        self.chkSLang.setObjectName(_fromUtf8("chkSLang"))
        self.horizontalLayout.addWidget(self.chkSLang)
        self.cboSLang = QtGui.QComboBox(self.layoutWidget1)
        self.cboSLang.setEnabled(False)
        self.cboSLang.setObjectName(_fromUtf8("cboSLang"))
        self.horizontalLayout.addWidget(self.cboSLang)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabSource, _fromUtf8(""))
        self.tabEncode = QtGui.QWidget()
        self.tabEncode.setObjectName(_fromUtf8("tabEncode"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabEncode)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 457, 521))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.grpVideo = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVideo.sizePolicy().hasHeightForWidth())
        self.grpVideo.setSizePolicy(sizePolicy)
        self.grpVideo.setMinimumSize(QtCore.QSize(0, 300))
        self.grpVideo.setObjectName(_fromUtf8("grpVideo"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.grpVideo)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 411, 281))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.cboVCodec = QtGui.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboVCodec.sizePolicy().hasHeightForWidth())
        self.cboVCodec.setSizePolicy(sizePolicy)
        self.cboVCodec.setMinimumSize(QtCore.QSize(150, 0))
        self.cboVCodec.setObjectName(_fromUtf8("cboVCodec"))
        self.horizontalLayout_5.addWidget(self.cboVCodec)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spnPasses = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnPasses.setMinimum(1)
        self.spnPasses.setObjectName(_fromUtf8("spnPasses"))
        self.horizontalLayout_5.addWidget(self.spnPasses)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.txtVBitrate = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVBitrate.sizePolicy().hasHeightForWidth())
        self.txtVBitrate.setSizePolicy(sizePolicy)
        self.txtVBitrate.setMinimumSize(QtCore.QSize(40, 0))
        self.txtVBitrate.setMaximumSize(QtCore.QSize(70, 16777215))
        self.txtVBitrate.setObjectName(_fromUtf8("txtVBitrate"))
        self.horizontalLayout_7.addWidget(self.txtVBitrate)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.btnAuto = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btnAuto.setObjectName(_fromUtf8("btnAuto"))
        self.horizontalLayout_7.addWidget(self.btnAuto)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.txtFilesize = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFilesize.sizePolicy().hasHeightForWidth())
        self.txtFilesize.setSizePolicy(sizePolicy)
        self.txtFilesize.setMinimumSize(QtCore.QSize(40, 0))
        self.txtFilesize.setMaximumSize(QtCore.QSize(70, 16777215))
        self.txtFilesize.setObjectName(_fromUtf8("txtFilesize"))
        self.horizontalLayout_7.addWidget(self.txtFilesize)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.cboVProfile = QtGui.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboVProfile.sizePolicy().hasHeightForWidth())
        self.cboVProfile.setSizePolicy(sizePolicy)
        self.cboVProfile.setMinimumSize(QtCore.QSize(200, 0))
        self.cboVProfile.setObjectName(_fromUtf8("cboVProfile"))
        self.horizontalLayout_9.addWidget(self.cboVProfile)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_9.addWidget(self.label_16)
        self.spnMotion = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnMotion.setMinimum(1)
        self.spnMotion.setMaximum(4)
        self.spnMotion.setProperty("value", 3)
        self.spnMotion.setObjectName(_fromUtf8("spnMotion"))
        self.horizontalLayout_9.addWidget(self.spnMotion)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkCrop = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.chkCrop.setChecked(True)
        self.chkCrop.setObjectName(_fromUtf8("chkCrop"))
        self.gridLayout.addWidget(self.chkCrop, 1, 0, 1, 1)
        self.spnWidth = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnWidth.setMaximum(9999)
        self.spnWidth.setObjectName(_fromUtf8("spnWidth"))
        self.gridLayout.addWidget(self.spnWidth, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.spnHorizontal = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnHorizontal.setMaximum(9999)
        self.spnHorizontal.setObjectName(_fromUtf8("spnHorizontal"))
        self.gridLayout.addWidget(self.spnHorizontal, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.btnCropDetect = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btnCropDetect.setObjectName(_fromUtf8("btnCropDetect"))
        self.gridLayout.addWidget(self.btnCropDetect, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1)
        self.spnHeight = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnHeight.setMaximum(9999)
        self.spnHeight.setObjectName(_fromUtf8("spnHeight"))
        self.gridLayout.addWidget(self.spnHeight, 2, 2, 1, 1)
        self.spnVertical = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnVertical.setMaximum(9999)
        self.spnVertical.setObjectName(_fromUtf8("spnVertical"))
        self.gridLayout.addWidget(self.spnVertical, 2, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.line_3 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chkScale = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.chkScale.setEnabled(True)
        self.chkScale.setChecked(True)
        self.chkScale.setObjectName(_fromUtf8("chkScale"))
        self.gridLayout_3.addWidget(self.chkScale, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.spnScaleW = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnScaleW.setEnabled(True)
        self.spnScaleW.setMaximum(9999)
        self.spnScaleW.setObjectName(_fromUtf8("spnScaleW"))
        self.gridLayout_3.addWidget(self.spnScaleW, 0, 2, 1, 1)
        self.spnScaleH = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.spnScaleH.setEnabled(False)
        self.spnScaleH.setMaximum(9999)
        self.spnScaleH.setObjectName(_fromUtf8("spnScaleH"))
        self.gridLayout_3.addWidget(self.spnScaleH, 0, 4, 1, 1)
        self.chkLockAR = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.chkLockAR.setEnabled(True)
        self.chkLockAR.setChecked(True)
        self.chkLockAR.setObjectName(_fromUtf8("chkLockAR"))
        self.gridLayout_3.addWidget(self.chkLockAR, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.grpVideo)
        self.grpAudio = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAudio.sizePolicy().hasHeightForWidth())
        self.grpAudio.setSizePolicy(sizePolicy)
        self.grpAudio.setMinimumSize(QtCore.QSize(0, 100))
        self.grpAudio.setObjectName(_fromUtf8("grpAudio"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.grpAudio)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 411, 80))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.cboACodec = QtGui.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboACodec.sizePolicy().hasHeightForWidth())
        self.cboACodec.setSizePolicy(sizePolicy)
        self.cboACodec.setMinimumSize(QtCore.QSize(200, 0))
        self.cboACodec.setObjectName(_fromUtf8("cboACodec"))
        self.horizontalLayout_8.addWidget(self.cboACodec)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_10.addWidget(self.label_17)
        self.cboAProfile = QtGui.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAProfile.sizePolicy().hasHeightForWidth())
        self.cboAProfile.setSizePolicy(sizePolicy)
        self.cboAProfile.setMinimumSize(QtCore.QSize(200, 0))
        self.cboAProfile.setObjectName(_fromUtf8("cboAProfile"))
        self.horizontalLayout_10.addWidget(self.cboAProfile)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addWidget(self.grpAudio)
        self.line_4 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.txtOutputdir = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOutputdir.sizePolicy().hasHeightForWidth())
        self.txtOutputdir.setSizePolicy(sizePolicy)
        self.txtOutputdir.setMinimumSize(QtCore.QSize(230, 0))
        self.txtOutputdir.setObjectName(_fromUtf8("txtOutputdir"))
        self.horizontalLayout_6.addWidget(self.txtOutputdir)
        self.btnSelDir = QtGui.QPushButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/folder-blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSelDir.setIcon(icon1)
        self.btnSelDir.setObjectName(_fromUtf8("btnSelDir"))
        self.horizontalLayout_6.addWidget(self.btnSelDir)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_11.addWidget(self.label_18)
        self.txtFileName = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtFileName.sizePolicy().hasHeightForWidth())
        self.txtFileName.setSizePolicy(sizePolicy)
        self.txtFileName.setMinimumSize(QtCore.QSize(315, 0))
        self.txtFileName.setStatusTip(_fromUtf8(""))
        self.txtFileName.setObjectName(_fromUtf8("txtFileName"))
        self.horizontalLayout_11.addWidget(self.txtFileName)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.chkSaveSettings = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkSaveSettings.setChecked(True)
        self.chkSaveSettings.setTristate(False)
        self.chkSaveSettings.setObjectName(_fromUtf8("chkSaveSettings"))
        self.verticalLayout_3.addWidget(self.chkSaveSettings)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnStart = QtGui.QPushButton(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnStart.setPalette(palette)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout_3.addWidget(self.btnStart)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabEncode, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.btnExit = QtGui.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon2)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout_4.addWidget(self.btnExit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        BR_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BR_MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BR_MainWindow.setStatusBar(self.statusbar)
        self.actionE_xit = QtGui.QAction(BR_MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))

        self.retranslateUi(BR_MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkALang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cboALang.setEnabled)
        QtCore.QObject.connect(self.chkSLang, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cboSLang.setEnabled)
        QtCore.QObject.connect(self.chkCrop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spnWidth.setEnabled)
        QtCore.QObject.connect(self.chkCrop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spnHorizontal.setEnabled)
        QtCore.QObject.connect(self.chkCrop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.btnCropDetect.setEnabled)
        QtCore.QObject.connect(self.chkCrop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spnHeight.setEnabled)
        QtCore.QObject.connect(self.chkCrop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spnVertical.setEnabled)
        QtCore.QObject.connect(self.chkScale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.spnScaleW.setEnabled)
        QtCore.QObject.connect(self.chkScale, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkLockAR.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(BR_MainWindow)
        BR_MainWindow.setTabOrder(self.cboVCodec, self.spnPasses)
        BR_MainWindow.setTabOrder(self.spnPasses, self.txtVBitrate)
        BR_MainWindow.setTabOrder(self.txtVBitrate, self.btnAuto)
        BR_MainWindow.setTabOrder(self.btnAuto, self.txtFilesize)
        BR_MainWindow.setTabOrder(self.txtFilesize, self.cboVProfile)
        BR_MainWindow.setTabOrder(self.cboVProfile, self.spnMotion)
        BR_MainWindow.setTabOrder(self.spnMotion, self.chkCrop)
        BR_MainWindow.setTabOrder(self.chkCrop, self.spnWidth)
        BR_MainWindow.setTabOrder(self.spnWidth, self.spnHorizontal)
        BR_MainWindow.setTabOrder(self.spnHorizontal, self.btnCropDetect)
        BR_MainWindow.setTabOrder(self.btnCropDetect, self.spnHeight)
        BR_MainWindow.setTabOrder(self.spnHeight, self.spnVertical)
        BR_MainWindow.setTabOrder(self.spnVertical, self.chkScale)
        BR_MainWindow.setTabOrder(self.chkScale, self.spnScaleW)
        BR_MainWindow.setTabOrder(self.spnScaleW, self.spnScaleH)
        BR_MainWindow.setTabOrder(self.spnScaleH, self.chkLockAR)
        BR_MainWindow.setTabOrder(self.chkLockAR, self.cboACodec)
        BR_MainWindow.setTabOrder(self.cboACodec, self.cboAProfile)
        BR_MainWindow.setTabOrder(self.cboAProfile, self.txtOutputdir)
        BR_MainWindow.setTabOrder(self.txtOutputdir, self.btnSelDir)
        BR_MainWindow.setTabOrder(self.btnSelDir, self.txtFileName)
        BR_MainWindow.setTabOrder(self.txtFileName, self.btnStart)
        BR_MainWindow.setTabOrder(self.btnStart, self.btnExit)
        BR_MainWindow.setTabOrder(self.btnExit, self.DVDTree)
        BR_MainWindow.setTabOrder(self.DVDTree, self.cboSLang)
        BR_MainWindow.setTabOrder(self.cboSLang, self.cboALang)
        BR_MainWindow.setTabOrder(self.cboALang, self.tabWidget)
        BR_MainWindow.setTabOrder(self.tabWidget, self.chkALang)
        BR_MainWindow.setTabOrder(self.chkALang, self.chkSLang)

    def retranslateUi(self, BR_MainWindow):
        BR_MainWindow.setWindowTitle(_translate("BR_MainWindow", "Baserip", None))
        self.chkALang.setText(_translate("BR_MainWindow", "Audio Language", None))
        self.chkSLang.setText(_translate("BR_MainWindow", "Subtitle Language", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSource), _translate("BR_MainWindow", "Source", None))
        self.grpVideo.setTitle(_translate("BR_MainWindow", "Video", None))
        self.label.setText(_translate("BR_MainWindow", "Codec", None))
        self.label_2.setText(_translate("BR_MainWindow", "Passes", None))
        self.label_3.setText(_translate("BR_MainWindow", "Bitrate", None))
        self.label_4.setText(_translate("BR_MainWindow", "kbps", None))
        self.btnAuto.setText(_translate("BR_MainWindow", "Auto", None))
        self.label_13.setText(_translate("BR_MainWindow", "Filesize", None))
        self.label_14.setText(_translate("BR_MainWindow", "MB", None))
        self.label_15.setText(_translate("BR_MainWindow", "Profile", None))
        self.label_16.setText(_translate("BR_MainWindow", "Motion", None))
        self.chkCrop.setText(_translate("BR_MainWindow", "Crop", None))
        self.label_5.setText(_translate("BR_MainWindow", "Width", None))
        self.label_6.setText(_translate("BR_MainWindow", "Horizontal", None))
        self.btnCropDetect.setText(_translate("BR_MainWindow", "Detect", None))
        self.label_7.setText(_translate("BR_MainWindow", "Height", None))
        self.label_8.setText(_translate("BR_MainWindow", "Vertical", None))
        self.chkScale.setText(_translate("BR_MainWindow", "Scale", None))
        self.label_9.setText(_translate("BR_MainWindow", "Width", None))
        self.label_10.setText(_translate("BR_MainWindow", "Height", None))
        self.chkLockAR.setText(_translate("BR_MainWindow", "Lock Aspect Ratio", None))
        self.grpAudio.setTitle(_translate("BR_MainWindow", "Audio", None))
        self.label_12.setText(_translate("BR_MainWindow", "Codec", None))
        self.label_17.setText(_translate("BR_MainWindow", "Profile", None))
        self.label_11.setText(_translate("BR_MainWindow", "Output Directory", None))
        self.txtOutputdir.setToolTip(_translate("BR_MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">%T</span> - Title of the track</p><p><span style=\" font-weight:600;\">%N</span> - Number of the selected track (useful for batch encoding)</p><p><span style=\" font-weight:600;\">%L</span> - Length of the selected track</p><p><span style=\" font-weight:600;\">%f </span>- The first letter of the title (useful for organisation)</p><p><span style=\" font-weight:600;\">%b</span> - Bitrate of the video stream</p><p><span style=\" font-weight:600;\">%l</span> - Language of the audio track</p><p><span style=\" font-weight:600;\">%w</span> - Width of the video output</p><p><span style=\" font-weight:600;\">%h</span> - Height of the video output</p></body></html>", None))
        self.btnSelDir.setText(_translate("BR_MainWindow", "Select", None))
        self.label_18.setText(_translate("BR_MainWindow", "Output File Name", None))
        self.txtFileName.setToolTip(_translate("BR_MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">%T</span> - Title of the track</p><p><span style=\" font-weight:600;\">%N</span> - Number of the selected track (useful for batch encoding)</p><p><span style=\" font-weight:600;\">%L</span> - Length of the selected track</p><p><span style=\" font-weight:600;\">%f </span>- The first letter of the title (useful for organisation)</p><p><span style=\" font-weight:600;\">%b</span> - Bitrate of the video stream</p><p><span style=\" font-weight:600;\">%l</span> - Language of the audio track</p><p><span style=\" font-weight:600;\">%w</span> - Width of the video output</p><p><span style=\" font-weight:600;\">%h</span> - Height of the video output</p></body></html>", None))
        self.txtFileName.setText(_translate("BR_MainWindow", "%T_%bkbps-%wX%h", None))
        self.chkSaveSettings.setText(_translate("BR_MainWindow", "Save Settings", None))
        self.btnStart.setText(_translate("BR_MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEncode), _translate("BR_MainWindow", "Encode", None))
        self.btnExit.setText(_translate("BR_MainWindow", "Exit", None))
        self.actionE_xit.setText(_translate("BR_MainWindow", "E&xit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    BR_MainWindow = QtGui.QMainWindow()
    ui = Ui_BR_MainWindow()
    ui.setupUi(BR_MainWindow)
    BR_MainWindow.show()
    sys.exit(app.exec_())

