#! /usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Replacement (unofficial) `setup.py` for the `event` module.
Automatically generated by `openerpdist`. See http://noteed.com/openerpdist/.
"""

import setuptools

setuptools.setup(
    name = "openerp-event",
    version = "7.0.355",
    description = "Events Organisation",
    long_description = 
"""

Organization and management of Events.
======================================

The event module allows you to efficiently organise events and all related tasks: planification, registration tracking,
attendances, etc.

Key Features
------------
* Manage your Events and Registrations
* Use emails to automatically confirm and send acknowledgements for any event registration
""",
    url = "",
    author = "OpenERP SA",
    author_email = "TODO",
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3",
        "Natural Language :: English",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    license = "AGPL-3",
    package_dir = {
        'openerp.addons.event': ".",
    },
    packages = ["openerp.addons.event","openerp.addons.event.report","openerp.addons.event.wizard"],
    package_data = {
        'openerp.addons.event': ["i18n/*.po*","board_association_view.xml","event_demo.xml","event_view.xml","res_partner_view.xml","email_template.xml","event_data.xml","images/events_kanban.jpeg","images/3_registrations.jpeg","images/2_events.jpeg","images/1_event_type_list.jpeg","images/icon.png","static/src/img/icon.png","i18n/sk.po","i18n/id.po","i18n/hr.po","i18n/da.po","i18n/sl.po","i18n/es_MX.po","i18n/ru.po","i18n/zh_TW.po","i18n/cs.po","i18n/sq.po","i18n/fi.po","i18n/pt_BR.po","i18n/ko.po","i18n/gu.po","i18n/bg.po","i18n/es_VE.po","i18n/tlh.po","i18n/ja.po","i18n/ro.po","i18n/es_AR.po","i18n/hi.po","i18n/sr@latin.po","i18n/es.po","i18n/mn.po","i18n/it.po","i18n/nl.po","i18n/sv.po","i18n/es_EC.po","i18n/uk.po","i18n/bs.po","i18n/tr.po","i18n/de.po","i18n/et.po","i18n/sr.po","i18n/lt.po","i18n/hu.po","i18n/vi.po","i18n/el.po","i18n/mk.po","i18n/ca.po","i18n/fr.po","i18n/zh_CN.po","i18n/pl.po","i18n/nl_BE.po","i18n/nb.po","i18n/ar.po","i18n/pt.po","i18n/es_CR.po","test/ui/demo_data.yml","test/ui/duplicate_event.yml","test/process/event_draft2done.yml","security/ir.model.access.csv","security/event_security.xml","report/report_event_registration_view.xml","wizard/event_confirm_view.xml","security/event_security.xml","security/ir.model.access.csv","wizard/event_confirm_view.xml","event_view.xml","event_data.xml","report/report_event_registration_view.xml","board_association_view.xml","res_partner_view.xml","email_template.xml","event_demo.xml","static/src/css/event.css"],
    },
    install_requires = ["openerp-base-setup","openerp-board","openerp-email-template"],
    tests_require = ["unittest2"],
)
