__version__ = "0.1.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '7c942cb390324da4ecc97e28ab41619b7aad7254'
__git_head_subject__ = 'fixing handle pointers on 64bit platforms'
__git_head_message__ = ''
__git_dirty_diff__ = ''