language: python
python:
  - 2.7

install:
  - make python=$( which python ) .installed.cfg

script:
  - make coverage

notifications:
  irc:
    channels:
      - "irc.freenode.org#niteoweb"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
