__version__ = "0.2.7"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.7)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e7e8989d40cbc6eec82fe35dc9cbbec21b64eb3e'
__git_head_subject__ = 'Finished release v0.2.7.'
__git_head_message__ = '* release/v0.2.7:\n  buildout.cfg: adding setuptools to requirements\n  buildout.cfg: remove distribute from requirements'
__git_dirty_diff__ = ''